In [2]:
import pandas as pd
dataset=pd.read_csv('Placement_Data_Full_Class.csv')
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [ ]:
## Find similarity between Commerce and science group student's mba_p marks
## we use Independant - Unpaired - Ttest - to find similarity between two different groups with same condition
## p_value range should be less 5% or 0.05, for high similarities

In [4]:
dataset.dropna(inplace=True)
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
7,8,M,82.00,Central,64.00,Central,Science,66.00,Sci&Tech,Yes,67.0,Mkt&Fin,62.14,Placed,252000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,210,M,62.00,Central,72.00,Central,Commerce,65.00,Comm&Mgmt,No,67.0,Mkt&Fin,56.49,Placed,216000.0
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0

In [7]:
from scipy.stats import ttest_ind
Commerce = dataset[dataset["hsc_s"]=='Commerce']["mba_p"]
Science = dataset[dataset["hsc_s"]=='Science']["mba_p"]
ttest_ind(Commerce,Science)

Ttest_indResult(statistic=-1.2400084195296086, pvalue=0.21704661994731714)

In [ ]:
## In the result, p_value is 21% which is not in acceptable range, so there are more differences in the 
## mba_p marks between Commerce and Science groups students of hsc

In [ ]:
## Find similarity between Commerce group student's mba_p and etest_p marks
## we use dependant - paired - Ttest - to find similarity with in same group with different conditions
## p_value range should be less 5% or 0.05, for high similarities

In [8]:
from scipy.stats import ttest_rel
Commerce = dataset[dataset["hsc_s"]=='Commerce']["etest_p"]
Commerce1 = dataset[dataset["hsc_s"]=='Commerce']["mba_p"]
ttest_rel(Commerce,Commerce1)

Ttest_relResult(statistic=7.561268876092879, pvalue=6.62578075563851e-11)

In [ ]:
## In the result, p_value is 662% which is not in acceptable range, so the differences between
## mba_p and etest_p marks of Commerce group students of hsc is way higher

In [ ]:
## CALCULATE Anavo - Analysis of Variance

In [ ]:
##calculate one way classification

In [ ]:
## H0- Null Hypothesis- There is no significant difference between columns 'ssc_p','hsc_p','degree_p'
## H1- Alternate Hypothesis- There are significant difference between columns 'ssc_p','hsc_p','degree_p'

In [11]:
import pandas as pd
dataset=pd.read_csv('Placement_Data_Full_Class.csv')

In [12]:
from scipy.stats import stats
stats.f_oneway(dataset['ssc_p'],dataset['hsc_p'],dataset['degree_p'])

F_onewayResult(statistic=0.6719700864663097, pvalue=0.5110602818995302)

In [ ]:
Here, we see the pvalue is not <= 0.05,so H0 Null hypothesis is rejected and H1 Alternate hypothesis is accepted.
Hence there are significant difference between columns 'ssc_p','hsc_p','degree_p'

In [ ]:
## calculate two way classification

In [ ]:
##Gender:
## H0- Null Hypothesis- There is no significant differences in ssc_p marks due to 'gender'
## H1- Alternate Hypothesis- There are significant differences in ssc_p marks due to 'gender'

##ssc_b
## H0- Null Hypothesis- There is no significant differences in ssc_p marks due to 'ssc_b'
## H1- Alternate Hypothesis- There are significant differences in ssc_p marks due to'ssc_b'

In [13]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
df = dataset
model = ols('ssc_p ~ C(gender) * C(ssc_b)', data=df).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

print(anova_table)

                          sum_sq     df         F    PR(>F)
C(gender)             127.317936    1.0  1.092851  0.297036
C(ssc_b)              346.687640    1.0  2.975842  0.085980
C(gender):C(ssc_b)     39.207156    1.0  0.336540  0.562452
Residual            24581.647858  211.0       NaN       NaN

In [ ]:
## gender:
## Since P-value 0.297036 > 0.05, we accept H1. So there are significant differences in ssc_p marks due to 'gender'

##ssc_b
## Since P-value 0.085980 > 0.05, we accept H1. So there are significant differences in ssc_p marks due to'ssc_b'