In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio

pio.renderers.default='svg'

In [2]:
##!pip install plotly

In [ ]:
## to view complete list of output
"""
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)
"""

In [3]:
raw_df=pd.read_csv("Zomato_Mumbai_Dataset.csv",delimiter='|')

In [4]:
raw_df.head()

,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Mumbai,First International Financial Centre-- Bandra ...,https://www.zomato.com/mumbai/hitchki-bandra-k...,1,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mumbai,Mahim,https://www.zomato.com/mumbai/baba-falooda-mah...,1,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723
2,Chin Chin Chu,1800,"Asian,Chinese",Mumbai,Juhu,https://www.zomato.com/mumbai/chin-chin-chu-ju...,1,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337
3,Butterfly High,1000,Modern Indian,Mumbai,Bandra Kurla Complex,https://www.zomato.com/mumbai/butterfly-high-b...,1,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Mumbai,Bandra Kurla Complex,https://www.zomato.com/mumbai/bkc-dive-bandra-...,1,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995

In [5]:
## getting basic info about the dataset

In [6]:
raw_df.shape

(15081, 12)

In [7]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15081 entries, 0 to 15080
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             15081 non-null  object
 1   PRICE            15080 non-null  object
 2   CUSINE_CATEGORY  15079 non-null  object
 3   CITY             15080 non-null  object
 4   REGION           15080 non-null  object
 5   URL              15080 non-null  object
 6   PAGE NO          15080 non-null  object
 7   CUSINE TYPE      15080 non-null  object
 8   TIMING           15015 non-null  object
 9   RATING_TYPE      15080 non-null  object
 10  RATING           15080 non-null  object
 11  VOTES            15080 non-null  object
dtypes: object(12)
memory usage: 1.4+ MB

In [8]:
raw_df.describe()

,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
count,15081,15080,15079,15080,15080,15080,15080,15080,15015,15080,15080,15080
unique,12720,67,3183,2,241,13823,944,23,2551,32,35,1124
top,NAME,400,CUSINE_CATEGORY,Mumbai,REGION,URL,PAGE NO,Quick Bites,11am to 11pm(Mon-Sun),Average,-,-
freq,942,2042,942,14138,942,942,942,5262,1192,5112,2360,2360

In [9]:
##Cleaning dataset

In [10]:
##a.removing redundant rows

In [11]:
##wrong_data=raw_df[raw_df["PAGE NO"]=="PAGE NO"]

In [12]:
#raw_df=raw_df[~wrong_data]
raw_df = raw_df[raw_df["PAGE NO"] != "PAGE NO"]

In [13]:
#dropping columns which are not needed for analysis
raw_df.drop(['URL','PAGE NO','CITY'],axis=1,inplace=True)

In [16]:
raw_df.head()

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995

In [ ]:
##b.REMOVING NULL RECORDS

In [17]:
raw_df.isnull().sum()

NAME                0
PRICE               1
CUSINE_CATEGORY     2
REGION              1
CUSINE TYPE         1
TIMING             66
RATING_TYPE         1
RATING              1
VOTES               1
dtype: int64

In [19]:
raw_df[raw_df['PRICE'].isnull()]

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15080,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
## dropping the above row from dataset

raw_df=raw_df.drop(labels=15080,axis=0)

In [22]:
## replacing other null records with NA
raw_df.fillna("NA", inplace=True)

In [23]:
raw_df.isnull().sum()

NAME               0
PRICE              0
CUSINE_CATEGORY    0
REGION             0
CUSINE TYPE        0
TIMING             0
RATING_TYPE        0
RATING             0
VOTES              0
dtype: int64

In [30]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14138 entries, 0 to 15079
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             14138 non-null  object
 1   PRICE            14138 non-null  object
 2   CUSINE_CATEGORY  14138 non-null  object
 3   REGION           14138 non-null  object
 4   CUSINE TYPE      14138 non-null  object
 5   TIMING           14138 non-null  object
 6   RATING_TYPE      14138 non-null  object
 7   RATING           14138 non-null  object
 8   VOTES            14138 non-null  object
dtypes: object(9)
memory usage: 1.1+ MB

In [ ]:
#converting numerical columns to numeric datatype

In [47]:
# Checking for text values in the column before converting it to numeric datatype

##raw_df["PRICE"].value_counts()

raw_df[pd.to_numeric(raw_df["PRICE"], errors='coerce').isna()]

Empty DataFrame
Columns: [NAME, PRICE, CUSINE_CATEGORY, REGION, CUSINE TYPE, TIMING, RATING_TYPE, RATING, VOTES]
Index: []

In [42]:
#This confirms column has only numeric values

In [53]:
# Checking for text values in the column before converting it to numeric datatype

##raw_df["Rating"].value_counts()

raw_df[pd.to_numeric(raw_df["RATING"], errors='coerce').isna()]

Empty DataFrame
Columns: [NAME, PRICE, CUSINE_CATEGORY, REGION, CUSINE TYPE, TIMING, RATING_TYPE, RATING, VOTES]
Index: []

In [52]:
raw_df["RATING"].value_counts()

0      3370
3.5    1094
3.4    1036
3.6     960
3.3     926
3.7     917
3.2     801
3.8     782
3.1     734
3.0     622
3.9     596
2.9     409
4.0     408
2.8     309
4.1     298
4.2     199
2.7     170
4.3     148
4.4      99
2.6      77
4.5      46
2.5      39
4.6      32
2.4      26
4.7      13
2.3      10
2.1       5
4.8       4
2.2       4
4.9       2
1.8       1
2.0       1
Name: RATING, dtype: int64

In [51]:
#replacing text values with 0
raw_df["RATING"].replace(to_replace=['-','Opening','NEW'],value=0,inplace=True)

In [54]:
# Checking for text values in the column before converting it to numeric datatype

##raw_df["VOTES"].value_counts()

raw_df[pd.to_numeric(raw_df["VOTES"], errors='coerce').isna()]

                                                   NAME PRICE  \
32                        Hotel Annapoorna Refreshments   400
34                                            Biryani 9   600
36                                    D Fusion Flavours   350
39                                         Nation Tadka   400
83                                 Link  Way Restaurant   500
84                                 Lajawab Kabab Corner   150
91                                      Sai Leela Hotel   600
105                                    The Dark Kitchen   600
106                                              Mokart   200
107                                 The Bukhara Kitchen   400
109                            Chicago Waffles & Shakes   150
116                                    Goregaon Kitchen   400
169                               Red Chilly Restaurant   400
170                                        Roll Factory   250
208                                          Food Magic   250
227                                         Green Tadka   700
234                                              Daawat   600
258                                           Nakabandi   500
286                                        The Post Box   750
305                                           Le Gateau   400
320                  Kulfi Shakes - By The Foodie Nawab   300
321                                         Planet Food   500
322                           Chandok Shubham Fast Food   300
323                                     Chaudhary Tadka   450
325                           D Katta Family Restaurant   400
345                         Asian Spices The Restaurant   500
348                                         Chill'Antro   600
354                                        101's Maggie   200
364                                     Burrito Factory   650
366                                    Bhagat Tarachand   450
390                            Saikrupa Amritsar Kulcha   150
402                                               Burrp   800
403                                           Bismillah   500
404                                      The Matka Chef   250
405                             Baba Hotel & Lunch Home   400
419                                      Chowpaty Kulfi   150
429                                          Noor Sahab   800
446                                          Xotik Cafe   600
456                                        Mumbai Magic   400
476                      Cafe Vrindavan Pure Vegetarian   500
489                               Choice Snacks Parlour   600
491                       Shaan  E Lucknow Tunday Kabab   300
502                                            Indichef   400
505                                        Juice Lounge   500
525                                        ChickenWalla   500
533                                               Box99   600
584                                        China Xpress   450
585                                          Beer Bites   800
596                                  Pegasus Brew House  1500
598                                        The BN Fries   150
614                                       The Body Chef   700
618                                          Jab We Met   300
635                                     Olive Fast Food   300
641                                 Callisto Bistro Bar  1000
652                                    My China Kitchen   300
653                                       Made In China   300
654                                    Hotel Super Bowl   300
656                                         Cake Street   200
707                                  The Bebe's Kitchen   500
713                                  Sarkar Food Corner   500
714                                            Ponchi's   400
749                        Detox Cold Pressed Juice Bar   300
761                                      Chit Chat Chai   350
774                                    Archie's Kitchen   250
786                         Halal The House Of Shawarma   150
795                            Madhuban Veg. Restaurant   500
796                                   Scooper N Shakker   200
829                                        # Spice Love   200
840                          Sai Krupa Bar & Restaurant   400
841                                         Samrat Yash   350
861                                    Ameixing Chinese   350
885                                       Choice Bakers   150
894                                             Sammy's   250
899                                     The Chef's Wife   500
914                     Tipsy Panda Asian Kitchen + Bar   800
931                                        Cafe Am 2 Pm   500
932                                          Dhaba Cafe   500
937                            BOGO Breakfast On The Go   300
961                                        9 Tea's Cafe   400
962                                          Madas Cafe   400
968                                          Rare Earth  1000
987                                           Juice Bar   400
996                                       Fork & Barrel  1100
1001                                            Merwans   150
1009                                       Golden China   250
1024                            Shree Krishna Fast Food   400
1025                                    London Flavours   200
1046                                  Captain's Gourmet   400
1052                        Yummyyyy Cakes & Chocolates   300
1060                                   Bhukkad Junction   600
1062                                     Sandwich Point   200
1077                      Konkani Haus Restaurant & Bar   800
1085                                    Bonfire Burgers   500
1098                                        Saladomania   350
1109                                       Aaichi Rasoi   500
1115                                     North Ka Tadka   150
1138           Sidhivinayak Refreshment - Ladha Pattice   100
1141                                    Food Burst Cafe   350
1142                                 Gargi's Milkshakes   250
1149                           Nambiar's Kerala Kitchen   400
1154                                 Brunch Food Studio   200
1190                                      Spicy Kitchen   300
1197                       Kool Point Kulfi & Ice Cream   300
1198                      Green Spice Family Restaurant   700
1200                                      KB 99 Kitchen   300
1201                             Vikas Restaurant & Bar   400
1211                                 Khan Sahab Kitchen   500
1246                                       Biryani King   250
1266                               The Ghee Dum Biryani   500
1326                                      Shreeji Thali   600
1349                                      Rollerz Joint   200
1356                                              Eatup   450
1363                                         F2 Kitchen   500
1376                             Arabian Cafe &  Eatery   450
1386                                     Relish Cherish   800
1398                                         Food Zamia   500
1420                                     Sukhi Ka Dhaba   400
1459                                       Lucky Darbar   400
1484                                 FOU The Crazy Cafe   600
1485                                     Drunken Monkey   400
1496                                         Carmiano'z   300
1510                                    The Conti House   500
1534                                   Ministry of Eggs   400
1537                          Hindustan New Food Corner   300
1547                                            Wok 444   600
1564                                    Vintage Kitchen   250
1569                                       Delta 9 Cafe  1000
1589                                           The Chef   700
1624                       Bharti's Cafe Sattu Bangs On   250
1628                              Fries Shakes And More   300
1673                             The Blend Express Cafe   600
1687                                      Vaishnu Hotel   500
1688                                      Santosh Hotel   300
1701                                      King Of China   300
1726                                       Global Tadka   300
1766                                       Sindhi Tadka  1000
1797                                              Sosho  1100
1803                                         Blue Basil   350
1876                                            Khaaloo   200
1894                                        Pokket Cafe   500
1900                            Hotel The Mann Chillies   300
1904                                  FC Friends Corner   300
1910                                         Fresh Food   400
1914                             SOY -Pan Asian Kitchen   800
1915                                   The Malvan Belly   300
1924                                         Oh! Bangla   300
1947                    Hotel Rajmudra Restaurant & Bar   800
1986                                      Wat-a-Biryani   500
1987                                        China Point   400
1994                                        Combos King   300
2018                     Jugaad The Street Food Kitchen   250
2023                                     Banarasi Foods   400
2030                                  Khalbatta Chicken   400
2042                          Raghuvanshi  Juice Corner   100
2043                                      Chicago Pizza   400
2044                                  Satvik Restaurant   300
2077                                   Radhika Pure Veg   400
2091                                        Pizza Vizza   400
2101                                      Mouth Melters   300
2105                                      Sher-A-Panjab   800
2154                                    Foody's Kitchen   300
2170                                     Healthy Living   600
2174                                  Deluxe Restaurant   400
2176                        The Neighbourhood Meat Mart   600
2215                                       Amir Tandoor   300
2221                              Food Bar Multicuisine   350
2246                                 Husaini Restaurant   300
2247              Shree Sharada Hotel Family Restaurant   300
2259                                    Jashn E Biryani   500
2261                                         Happy Eats   300
2316                                            O Cakes   400
2333                                        Top In Town  1000
2340              El Postre - The Little Baking Station   400
2341                                      Masala Street   500
2342                             Any Time Snacks Center   450
2403                                      Musculo Meals   400
2405                                       Bombay Rolls   250
2407                                     Om Food Corner   200
2410                                          81 Olives   300
2427                                   D Cake Creations   650
2474                                    Dolphin Kitchen   300
2480                                         YOS Theory   250
2483                                   Urban Lokal Cafe   350
2490                                    Natural Paratha   300
2493                                       Smoke N Fire   300
2494                                      Healthy Bites   200
2496                                  Quba Pizza & More   200
2519                                      Cafe Go Krazy   200
2524                         Love Ice Cream And Sundaes   100
2587                                            Sheetal   550
2616                                       Eat N Repeat   200
2638                                      Spice N Sprit   300
2677                                     Chaap Ki Chhap   600
2682                              B.A.B.A Night Cuisine   500
2700                                   O'Biryani by OYO   500
2705                                    Darbar E Pakwan   500
2721                                        Agari Queen   350
2762                                              Aroma   400
2793                    Gurudev Hotel Family Restaurant   400
2794                                    Twisting Scoops   350
2795                                       Namaste Chai   300
2854                                          Lazzatdar   300
2866                                  The Momo Junction   250
2871                                     Diet With Care   350
2876                                      Deshi Videshi   300
2894                            Parkar’s Fusion Kitchen   400
2930                 Jagdamba Bhelpuri & Sandwich House   150
2981                                      Jumbo Biryani   600
2984                                     Burger Station   300
2987                                           Eggcited   400
3010                                           One Self   300
3011                                         Agri Spice   500
3070                                     Hotel Trimurti   400
3093                                      Goli Vada Pav   150
3110                                       Naaz Kitchen   200
3125                                     Harish Kitchen   550
3126                                         ST Express   800
3153                                Aao Kabhi Haveli Pe   500
3154                           Memsaab Restaurant & Bar   600
3156                                Ambriona Chocolates   300
3165                                           Yaadgaar   400
3173                  Cup-A-Licious - Patisserie & Cafe   500
3176                                      Chef's Korean  1600
3188                                 Main Street Bakery   350
3208                                          Oh Eatery   600
3234                                      Marine Jewels   500
3235                                 Tiny Tasty Kitchen   500
3236                                        Masalaa Bay   300
3270                                     La Fruta Foods   200
3275                      Jagdish Chaurasia Pan Bhandar   150
3276                                  Chiff Chaff Foods   300
3285                                        Healthistan   500
3288                                         Lil Treats   200
3291                        Pichkari - Healthy Food Day   300
3296                                        Brestro Inn   300
3352                                     Sizzling Plate   400
3353                                         Mauli Cafe   300
3354                                     Meher Da Dhaba   250
3357                                       Secret Spice   300
3371                                Knock Knock Kitchen   500
3390      Samudra Multi Cuisine Family Restaurant & Bar   800
3393                                      German Bakery   800
3399                                       Bingo Burger   300
3421           Hotel Sudharshan Family Restaurant & Bar   600
3441                                Oho Thali & Tandoor   300
3442                                     Yogi's Kitchen   500
3459                                         Hot N Cool   300
3475                                      Hotel Aradhya   400
3476               Smile Groups Italian Pizza And Pasta   300
3510                      Red Phoenix Authentic Chinese   250
3573                                       Waffle Shack   400
3597                                    Chicken Delight   200
3598                                     Zaika Delhi Ka   800
3613                                    The Daily Baker   400
3646                                           Mr. Chef   500
3648                         Dittya Fast Food & Tandoor   500
3650                                        Haagen Dazs   800
3651                               The 90s Cake Gallery   500
3659                                         KP's Pizza   400
3675                                       Cake Me Home   300
3707                             Raju Chinese Fast Food   250
3708                                  Shree Datta Misal   100
3709                                        Lassi Chill   150
3761                                    The Food Affair   550
3762                                Ayyapan Dosa Centre   150
3776                                        Fat Punjabi   250
3778                                  D'Çomfort Gourmet   300
3784                    Darya Raja Sea Food Restaurants   400
3786                                      Eddie's Spice   600
3787                                      Chef's Corner   250
3813                                   New Great Punjab   300
3856                               Bansiwala Agra Petha   200
3858                                   Krishna Homemade   200
3859                                      Srirang Foods   250
3870                                   Star Garib Nawaz   400
3872                                   Star Garib Nawaz   400
3889                                 Delhi Food Factory   600
3892                               Same Place Same time  1200
3939                                       Curry Xpress   500
3940                                      Nachos & More   200
3981                             Dilawar Bhai's Biryani   250
3982                                           Foodstix  1700
3985                               Galaxy Snacks Corner   350
4037                                       Swad Veg Hub   150
4042                                     La Broast Food   300
4043                                  The Momos Machine   100
4096                                      Mom's Kitchen   300
4109                                     Bandra Hideout  2000
4114                             The Local Eatery House   500
4115                                  Take-Away-Express   400
4116                                    Swad Restauarnt   500
4118                                7 Swaad Food Corner   450
4132                                     Kwality Wall's   200
4144                               Neba- The Asian Cafe   400
4187                            Kebab & Biryani Station   350
4188                                 F3 House Of Hunger   400
4189                      Great Punjab Fast Food Corner   300
4190                                       Dum Biryanis   300
4193                                       Modern China   400
4228                                     Swayampak Ghar   250
4229                                       Mum Bai Toei   500
4231                                         Mad hunger   250
4246                                       Mum Bai Toei   500
4247                                     Swayampak Ghar   250
4248                            Kebab & Biryani Station   350
4250                      Great Punjab Fast Food Corner   300
4251                                       Dum Biryanis   300
4254                                       Modern China   400
4283                                    Arab Restaurant   700
4285             Kumba's Multicuisine Family Restaurant   600
4306                    Center Point Restaurant and Bar   800
4307                                        Ahlan Dubai   500
4308                                      Healthy Bites   250
4423                                              Sayes   550
4424                                        Fatty Patty   350
4426                                The Chicken Company   250
4483                                       Hotel Dwarka   400
4489                                     Burger Culture   250
4490                                Hrishi's Food Court   400
4502                                       Sams Kitchen   500
4512                                   Cafe Choco Craze   200

In [55]:
raw_df["VOTES"].value_counts()

-          2360
NEW         953
4           364
5           320
6           288
7           277
8           258
10          224
11          206
13          187
9           183
12          179
14          173
17          149
15          148
16          133
21          132
25          124
18          124
19          109
22          109
23          105
20          103
24          100
29           99
27           96
26           92
40           90
30           90
35           84
28           83
31           78
34           76
39           75
32           70
44           68
37           67
33           67
36           65
43           62
55           59
41           58
Opening      57
38           56
63           52
50           51
51           50
47           50
53           50
42           49
45           49
49           47
48           46
46           46
67           44
59           44
54           44
52           44
61           42
56           42
69           41
58           41
60           40
64           38
57           36
72           35
76           35
83           35
68           34
71           34
73           33
62           33
66           33
89           33
80           30
94           30
65           30
74           30
70           29
78           29
109          28
96           28
91           28
75           28
79           26
77           26
93           25
97           25
95           24
122          24
106          24
90           24
98           24
86           23
87           23
126          23
128          23
103          22
88           22
81           22
113          21
120          20
127          20
100          20
85           20
99           19
107          19
121          19
82           19
101          19
111          18
104          18
108          18
123          18
119          18
124          18
110          18
161          17
130          17
151          17
157          17
114          16
92           16
129          16
140          16
183          15
142          15
84           15
117          15
136          15
116          15
138          15
105          15
115          15
153          14
118          14
147          14
167          14
125          14
173          13
134          13
178          13
145          13
112          13
181          13
185          13
149          13
102          13
146          13
137          12
158          12
248          12
144          12
131          12
156          12
171          12
135          12
259          12
198          12
160          12
152          12
206          12
154          11
237          11
229          11
187          11
184          11
238          11
199          11
155          11
212          11
150          11
148          11
143          10
162          10
197          10
174          10
277          10
200          10
132          10
253          10
230          10
180          10
262          10
177          10
141          10
235          10
165          10
188           9
228           9
204           9
139           9
159           9
133           9
274           9
190           9
166           9
221           9
257           9
227           9
353           9
164           9
168           8
291           8
192           8
258           8
280           8
195           8
211           8
209           8
170           8
264           8
232           8
222           8
189           8
202           8
405           8
214           8
278           8
210           8
220           8
266           8
241           8
487           8
350           8
203           7
236           7
325           7
251           7
179           7
205           7
244           7
194           7
338           7
172           7
260           7
217           7
303           7
252           7
267           7
176           7
193           7
201           7
355           7
290           7
239           7
225           7
285           7
300           7
319           6
490           6
401           6
215           6
440           6
469           6
272           6
191           6
320           6
412           6
293           6
287           6
270           6
296           6
207           6
186           6
169           6
271           6
357           6
299           6
328           6
374           6
163           6
196           6
265           6
243           6
281           6
439           6
332           6
543           6
331           6
307           6
363           6
324           6
254           6
175           6
358           6
311           6
446           6
182           6
459           6
269           6
261           6
424           5
422           5
701           5
336           5
445           5
334           5
346           5
366           5
554           5
426           5
348           5
330           5
482           5
284           5
302           5
231           5
310           5
322           5
312           5
213           5
276           5
476           5
297           5
607           5
234           5
208           5
342           5
384           5
506           5
249           5
578           5
389           5
462           5
525           5
464           5
413           5
294           5
391           5
218           5
403           5
242           5
454           5
223           5
461           4
356           4
563           4
365           4
481           4
367           4
813           4
233           4
240           4
314           4
442           4
368           4
245           4
375           4
329           4
606           4
283           4
339           4
292           4
615           4
553           4
373           4
601           4
250           4
219           4
263           4
782           4
497           4
528           4
315           4
513           4
337           4
397           4
575           4
407           4
418           4
404           4
379           4
246           4
372           4
420           4
224           4
273           4
399           4
460           4
715           4
621           4
706           4
576           3
556           3
364           3
441           3
679           3
450           3
514           3
683           3
505           3
488           3
421           3
388           3
569           3
509           3
1063          3
457           3
288           3
551           3
306           3
351           3
541           3
247           3
571           3
279           3
848           3
489           3
434           3
473           3
354           3
443           3
598           3
604           3
466           3
359           3
343           3
376           3
425           3
796           3
494           3
938           3
484           3
304           3
410           3
380           3
550           3
686           3
1090          3
406           3
387           3
545           3
449           3
852           3
435           3
883           3
646           3
892           3
361           3
431           3
411           3
870           3
289           3
427           3
527           3
226           3
574           3
216           3
2             3
400           3
321           3
395           3
648           3
548           3
414           3
455           3
515           3
255           3
308           3
827           3
723           3
286           3
675           2
1934          2
432           2
1025          2
653           2
909           2
695           2
752           2
423           2
727           2
644           2
613           2
826           2
529           2
500           2
333           2
885           2
383           2
667           2
568           2
1132          2
970           2
858           2
517           2
918           2
891           2
889           2
544           2
816           2
605           2
719           2
693           2
521           2
470           2
1             2
428           2
877           2
1564          2
1064          2
945           2
745           2
728           2
419           2
654           2
579           2
465           2
298           2
451           2
814           2
595           2
1276          2
932           2
670           2
275           2
564           2
477           2
772           2
393           2
345           2
386           2
616           2
912           2
493           2
743           2
962           2
1107          2
436           2
511           2
1071          2
295           2
589           2
316           2
1320          2
347           2
555           2
485           2
415           2
326           2
726           2
1471          2
479           2
327           2
1038          2
531           2
1088          2
974           2
632           2
335           2
649           2
734           2
1842          2
614           2
483           2
478           2
519           2
438           2
953           2
382           2
622           2
1004          2
637           2
881           2
377           2
349           2
394           2
533           2
546           2
1349          2
580           2
516           2
831           2
1200          2
639           2
722           2
1323          2
937           2
795           2
396           2
301           2
371           2
552           2
305           2
369           2
581           2
691           2
761           2
256           2
323           2
915           2
657           2
662           2
2031          2
471           2
1035          2
898           2
1771          2
1048          2
911           2
1209          2
526           2
341           2
655           2
496           2
448           2
633           2
385           2
467           2
437           2
570           2
1176          2
641           2
402           2
536           2
904           2
409           2
1282          2
907           2
865           2
7327          1
1032          1
1165          1
390           1
969           1
352           1
504           1
699           1
8000          1
2214          1
1904          1
680           1
1829          1
1314          1
2748          1
1067          1
512           1
998           1
573           1
1356          1
1142          1
702           1
803           1
547           1
1701          1
4654          1
1052          1
1268          1
452           1
2115          1
2291          1
430           1
532           1
2953          1
1138          1
972           1
1292          1
2358          1
2260          1
817           1
602           1
1397          1
1672          1
1585          1
664           1
769           1
1655          1
1728          1
1463          1
1617          1
1395          1
2965          1
523           1
1040          1
854           1
688           1
1078          1
463           1
3090          1
871           1
1003          1
549           1
2156          1
1807          1
468           1
1548          1
989           1
753           1
507           1
590           1
1343          1
645           1
665           1
887           1
716           1
3265          1
997           1
1522          1
433           1
1194          1
1005          1
1236          1
1315          1
1635          1
1376          1
510           1
768           1
1554          1
495           1
773           1
927           1
725           1
825           1
603           1
1451          1
1250          1
1750          1
842           1
1552          1
1131          1
1321          1
894           1
2329          1
976           1
674           1
694           1
1480          1
4605          1
2069          1
2642          1
585           1
2530          1
629           1
313           1
1039          1
1331          1
1678          1
3404          1
2800          1
1270          1
593           1
2092          1
2881          1
3643          1
922           1
1027          1
2466          1
1653          1
992           1
956           1
1510          1
268           1
1337          1
840           1
2484          1
1121          1
1541          1
1213          1
855           1
10217         1
824           1
1291          1
2998          1
3191          1
3058          1
2161          1
1862          1
1415          1
1255          1
2663          1
1733          1
1722          1
3252          1
1527          1
942           1
1497          1
862           1
2334          1
1295          1
1229          1
746           1
1100          1
3642          1
2870          1
1310          1
2996          1
566           1
2595          1
1560          1
1135          1
2079          1
1533          1
625           1
634           1
2797          1
1214          1
1957          1
1577          1
1960          1
847           1
1023          1
596           1
741           1
1966          1
2301          1
1249          1
671           1
1128          1
1242          1
1130          1
1550          1
757           1
774           1
1662          1
567           1
3161          1
1518          1
1197          1
2119          1
799           1
681           1
791           1
381           1
1521          1
1498          1
1736          1
2002          1
1058          1
730           1
1442          1
1029          1
851           1
584           1
1553          1
2891          1
1775          1
2256          1
1099          1
1967          1
1437          1
697           1
1876          1
2224          1
2528          1
1113          1
833           1
317           1
983           1
447           1
766           1
828           1
1469          1
2792          1
1075          1
1018          1
2272          1
2356          1
2511          1
1854          1
3376          1
1922          1
1723          1
1778          1
821           1
1891          1
1155          1
472           1
1177          1
591           1
1519          1
1159          1
5995          1
874           1
1782          1
1085          1
2757          1
672           1
1117          1
1770          1
1103          1
732           1
1615          1
499           1
1495          1
1169          1
1674          1
2062          1
1600          1
2044          1
2460          1
2280          1
1608          1
1143          1
2755          1
1764          1
492           1
1154          1
3005          1
1335          1
2266          1
2660          1
1184          1
3437          1
754           1
755           1
1457          1
1848          1
530           1
1306          1
2042          1
398           1
572           1
2409          1
1524          1
1144          1
626           1
964           1
921           1
1646          1
785           1
698           1
707           1
663           1
771           1
682           1
1225          1
4337          1
522           1
872           1
7377          1
1963          1
788           1
1414          1
3389          1
2602          1
944           1
1345          1
534           1
1274          1
2023          1
1616          1
636           1
1240          1
583           1
811           1
3193          1
340           1
822           1
610           1
2345          1
2411          1
1737          1
416           1
759           1
876           1
731           1
2504          1
0             1
2300          1
1974          1
2090          1
3615          1
2645          1
676           1
914           1
965           1
1777          1
1427          1
7350          1
3338          1
740           1
4770          1
4194          1
957           1
3529          1
913           1
1289          1
429           1
1087          1
486           1
392           1
1251          1
1769          1
2001          1
1515          1
910           1
6024          1
815           1
1136          1
1844          1
3469          1
1686          1
861           1
609           1
1281          1
919           1
535           1
5805          1
3             1
760           1
1953          1
3263          1
660           1
3226          1
837           1
668           1
309           1
1031          1
643           1
718           1
884           1
1050          1
560           1
1351          1
838           1
2822          1
1338          1
1449          1
2430          1
1381          1
784           1
692           1
618           1
1613          1
1137          1
1047          1
4017          1
934           1
1187          1
1302          1
896           1
866           1
1440          1
1605          1
1788          1
453           1
524           1
2068          1
2127          1
748           1
1526          1
984           1
1341          1
2981          1
1089          1
729           1
1303          1
612           1
1794          1
661           1
1630          1
557           1
1561          1
1147          1
2735          1
1760          1
1810          1
1367          1
652           1
1043          1
2157          1
6539          1
518           1
3283          1
1326          1
4057          1
1044          1
2117          1
1010          1
2826          1
1648          1
1500          1
2347          1
592           1
627           1
2184          1
2238          1
631           1
1207          1
2060          1
2165          1
594           1
1134          1
1185          1
4024          1
712           1
537           1
1983          1
1462          1
857           1
2387          1
1015          1
1150          1
3163          1
520           1
993           1
1374          1
832           1
1506          1
878           1
588           1
779           1
4675          1
360           1
2231          1
2211          1
856           1
1709          1
790           1
767           1
5882          1
941           1
1012          1
805           1
1559          1
1116          1
1125          1
2293          1
844           1
1082          1
1689          1
597           1
Name: VOTES, dtype: int64

In [56]:
#replacing text values with 0
raw_df["VOTES"].replace(to_replace=['-','Opening','NEW'],value=0,inplace=True)

In [ ]:
#changing the datatype of numeric value column to numeric

In [58]:
raw_df["VOTES"]=raw_df["VOTES"].astype('int64')
raw_df["PRICE"]=raw_df["PRICE"].astype('int64')
raw_df["RATING"]=raw_df["RATING"].astype('float64')

In [59]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14138 entries, 0 to 15079
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             14138 non-null  object
 1   PRICE            14138 non-null  int64
 2   CUSINE_CATEGORY  14138 non-null  object
 3   REGION           14138 non-null  object
 4   CUSINE TYPE      14138 non-null  object
 5   TIMING           14138 non-null  object
 6   RATING_TYPE      14138 non-null  object
 7   RATING           14138 non-null  float64
 8   VOTES            14138 non-null  int64
dtypes: float64(1), int64(2), object(6)
memory usage: 1.1+ MB

In [ ]:
#working with TIMING column

In [61]:
raw_df["TIMING"].value_counts()

11am to 11pm(Mon-Sun)                                   1192
11am to 12midnight(Mon-Sun)                              632
12noon to 12midnight(Mon-Sun)                            467
11am to 1130pm(Mon-Sun)                                  309
10am to 10pm(Mon-Sun)                                    267
10am to 11pm(Mon-Sun)                                    227
10am to 12midnight(Mon-Sun)                              222
11am to 1230AM(Mon-Sun)                                  200
8am to 11pm(Mon-Sun)                                     174
11am to 1am(Mon-Sun)                                     172
9am to 11pm(Mon-Sun)                                     171
8am to 12midnight(Mon-Sun)                               162
12noon to 11pm(Mon-Sun)                                  161
9am to 12midnight(Mon-Sun)                               159
1130am to 1130pm(Mon-Sun)                                154
12noon to 1am(Mon-Sun)                                   136
7am to 11pm(Mon-Sun)                                     128
1130am to 12midnight(Mon-Sun)                            125
12noon to 1130pm(Mon-Sun)                                124
11am to 10pm(Mon-Sun)                                    119
9am to 10pm(Mon-Sun)                                     119
9am to 9pm(Mon-Sun)                                      117
7am to 12midnight(Mon-Sun)                               103
8am to 1130pm(Mon-Sun)                                   103
11am to 4pm,7pm to 12midnight(Mon-Sun)                   102
8am to 10pm(Mon-Sun)                                     100
12noon to 1230AM(Mon-Sun)                                 95
10am to 1130pm(Mon-Sun)                                   90
9am to 1130pm(Mon-Sun)                                    88
12noon to 4pm,7pm to 12midnight(Mon-Sun)                  68
10am to 8pm(Mon-Sun)                                      68
12noon to 130am(Mon-Sun)                                  67
1130am to 1230AM(Mon-Sun)                                 67
10am to 1230AM(Mon-Sun)                                   66
NA                                                        65
11am to 330pm,7pm to 1130pm(Mon-Sun)                      61
10am to 1am(Mon-Sun)                                      60
7am to 10pm(Mon-Sun)                                      57
1130am to 11pm(Mon-Sun)                                   54
11am to 4pm,7pm to 11pm(Mon-Sun)                          52
11am to 130am(Mon-Sun)                                    52
7am to 1130pm(Mon-Sun)                                    51
11am to 4am(Mon-Sun)                                      51
1030am to 12midnight(Mon-Sun)                             50
11am to 2am(Mon-Sun)                                      49
12noon to 330pm,7pm to 1130pm(Mon-Sun)                    48
11am to 3am(Mon-Sun)                                      47
10am to 1030pm(Mon-Sun)                                   47
1030am to 1130pm(Mon-Sun)                                 47
1030am to 1230AM(Mon-Sun)                                 46
1030am to 1030pm(Mon-Sun)                                 46
10am to 9pm(Mon-Sun)                                      45
9am to 1030pm(Mon-Sun)                                    42
1030am to 11pm(Mon-Sun)                                   41
24                                                        41
11am to 1030pm(Mon-Sun)                                   41
12noon to 330pm,7pm to 12midnight(Mon-Sun)                41
1130am to 330pm,630pm to 1130pm(Mon-Sun)                  40
1130am to 330pm,7pm to 1130pm(Mon-Sun)                    40
11am to 3pm,7pm to 11pm(Mon-Sun)                          40
11am to 9pm(Mon-Sun)                                      39
11am to 4pm,7pm to 1130pm(Mon-Sun)                        39
8am to 1030pm(Mon-Sun)                                    39
9am to 1am(Mon-Sun)                                       37
12noon to 2am(Mon-Sun)                                    37
12noon to 3am(Mon-Sun)                                    37
12noon to 10pm(Mon-Sun)                                   36
1130am to 1am(Mon-Sun)                                    36
9am to 1230AM(Mon-Sun)                                    35
12noon to 4am(Mon-Sun)                                    35
1pm to 12midnight(Mon-Sun)                                35
10am to 7pm(Mon-Sun)                                      33
10am to 130am(Mon-Sun)                                    33
930am to 1130pm(Mon-Sun)                                  32
6pm to 12midnight(Mon-Sun)                                32
830am to 1030pm(Mon-Sun)                                  31
12noon to 3pm,7pm to 12midnight(Mon-Sun)                  31
11am to 3pm,6pm to 12midnight(Mon-Sun)                    31
11am to 3pm,6pm to 11pm(Mon-Sun)                          30
4pm to 11pm(Mon-Sun)                                      30
1130am to 130am(Mon-Sun)                                  30
8am to 9pm(Mon-Sun)                                       29
11am to 330pm,7pm to 12midnight(Mon-Sun)                  29
1130am to 4pm,7pm to 12midnight(Mon-Sun)                  28
8am to 8pm(Mon-Sun)                                       28
830am to 11pm(Mon-Sun)                                    28
1pm to 1am(Mon-Sun)                                       28
1pm to 11pm(Mon-Sun)                                      27
11am to 3pm,7pm to 12midnight(Mon-Sun)                    27
12noon to 3pm,6pm to 12midnight(Mon-Sun)                  26
11am to 330pm,7pm to 11pm(Mon-Sun)                        25
4pm to 12midnight(Mon-Sun)                                25
10am to 6pm(Mon-Sun)                                      25
9am to 8pm(Mon-Sun)                                       25
1230pm to 1130pm(Mon-Sun)                                 24
930am to 12midnight(Mon-Sun)                              24
6am to 12midnight(Mon-Sun)                                24
12noon to 3pm,7pm to 11pm(Mon-Sun)                        23
1230pm to 1230AM(Mon-Sun)                                 23
730am to 11pm(Mon-Sun)                                    23
12noon to 4pm,7pm to 11pm(Mon-Sun)                        23
8am to 1230AM(Mon-Sun)                                    23
7am to 1am(Mon-Sun)                                       22
12noon to 4pm,7pm to 1130pm(Mon-Sun)                      22
5pm to 12midnight(Mon-Sun)                                22
830am to 12midnight(Mon-Sun)                              22
5pm to 11pm(Mon-Sun)                                      22
830am to 1130pm(Mon-Sun)                                  21
8am to 1am(Mon-Sun)                                       21
11am to 1145pm(Mon-Sun)                                   20
7pm to 4am(Mon-Sun)                                       20
11am to 330pm,630pm to 1130pm(Mon-Sun)                    20
730am to 1130pm(Mon-Sun)                                  20
8am to 2am(Mon-Sun)                                       20
11am to 3pm,7pm to 1130pm(Mon-Sun)                        19
730am to 12midnight(Mon-Sun)                              19
11am to 7pm(Mon-Sun)                                      19
12noon to 330pm,7pm to 1230AM(Mon-Sun)                    19
6pm to 11pm(Mon-Sun)                                      19
1230pm to 12midnight(Mon-Sun)                             18
730am to 1030pm(Mon-Sun)                                  18
1130am to 1030pm(Mon-Sun)                                 18
9am to 7pm(Mon-Sun)                                       18
12noon to 330pm,7pm to 11pm(Mon-Sun)                      18
1130am to 4am(Mon-Sun)                                    17
12noon to 4pm,7pm to 1230AM(Mon-Sun)                      17
12noon to 3pm,7pm to 1130pm(Mon-Sun)                      17
12noon to 1030pm(Mon-Sun)                                 17
12noon to 4pm,6pm to 12midnight(Mon-Sun)                  17
930am to 11pm(Mon-Sun)                                    17
5pm to 1130pm(Mon-Sun)                                    17
7am to 1030pm(Mon-Sun)                                    17
Closed(Mon),11am to 11pm(Tue-Sun)                         16
930am to 10pm(Mon-Sun)                                    16
7am to 9pm(Mon-Sun)                                       15
2pm to 11pm(Mon-Sun)                                      15
930am to 1030pm(Mon-Sun)                                  15
1230pm to 11pm(Mon-Sun)                                   15
7am to 1230AM(Mon-Sun)                                    15
1pm to 1130pm(Mon-Sun)                                    15
2pm to 12midnight(Mon-Sun)                                15
6am to 10pm(Mon-Sun)                                      14
7pm to 12midnight(Mon-Sun)                                14
1130am to 330pm,7pm to 12midnight(Mon-Sun)                14
11am to 4pm,6pm to 12midnight(Mon-Sun)                    14
8am to 130am(Mon-Sun)                                     14
11am to 8pm(Mon-Sun)                                      14
4pm to 1am(Mon-Sun)                                       14
730am to 10pm(Mon-Sun)                                    14
1030am to 1am(Mon-Sun)                                    14
6am to 11pm(Mon-Sun)                                      13
9am to 6pm(Mon-Sun)                                       13
4pm to 10pm(Mon-Sun)                                      13
11am to 4pm,7pm to 1230AM(Mon-Sun)                        13
3pm to 11pm(Mon-Sun)                                      13
1130am to 330pm,630pm to 12midnight(Mon-Sun)              12
1130am to 4pm,7pm to 1130pm(Mon-Sun)                      12
11am to 930pm(Mon-Sun)                                    12
11am to 330pm,7pm to 1230AM(Mon-Sun)                      12
7am to 4am(Mon-Sun)                                       12
12noon to 3pm,6pm to 11pm(Mon-Sun)                        12
830am to 10pm(Mon-Sun)                                    12
12noon to 330pm,6pm to 12midnight(Mon-Sun)                12
1230pm to 130am(Mon-Sun)                                  12
12noon to 330pm,630pm to 12midnight(Mon-Sun)              12
10am to 3am(Mon-Sun)                                      12
930am to 1230AM(Mon-Sun)                                  12
1130am to 4pm,630pm to 1130pm(Mon-Sun)                    11
11am to 330pm,6pm to 12midnight(Mon-Sun)                  11
6pm to 1am(Mon-Sun)                                       11
2pm to 1130pm(Mon-Sun)                                    11
9am to 4am(Mon-Sun)                                       11
12noon to 330pm,630pm to 1130pm(Mon-Sun)                  11
8am to 930pm(Mon-Sun)                                     11
7pm to 11pm(Mon-Sun)                                      10
1130am to 3pm,630pm to 12midnight(Mon-Sun)                10
11am to 4pm,6pm to 11pm(Mon-Sun)                          10
1030am to 130am(Mon-Sun)                                  10
Closed(Mon),12noon to 11pm(Tue-Sun)                       10
5pm to 10pm(Mon-Sun)                                      10
4pm to 1230AM(Mon-Sun)                                    10
1230pm to 1am(Mon-Sun)                                    10
7pm to 5am(Mon-Sun)                                       10
11am to 4pm,630pm to 1130pm(Mon-Sun)                      10
6pm to 4am(Mon-Sun)                                       10
12noon to 4pm,7pm to 1am(Mon-Sun)                         10
1030am to 10pm(Mon-Sun)                                    9
1130am to 10pm(Mon-Sun)                                    9
930am to 930pm(Mon-Sun)                                    9
8am to 830pm(Mon-Sun)                                      9
1130am to 330pm,6pm to 1130pm(Mon-Sun)                     9
6pm to 1130pm(Mon-Sun)                                     9
8am to 3am(Mon-Sun)                                        9
12noon to 330pm,7pm to 1am(Mon-Sun)                        9
11am to 330pm,630pm to 12midnight(Mon-Sun)                 9
12noon to 4pm,7pm to 130am(Mon-Sun)                        9
6am to 1130pm(Mon-Sun)                                     9
10am to 930pm(Mon-Sun)                                     9
6am to 1am(Mon-Sun)                                        9
11am to 4pm,6pm to 1130pm(Mon-Sun)                         9
530pm to 12midnight(Mon-Sun)                               9
9am to 9pm(Mon-Sat),Closed(Sun)                            9
12noon to 3pm,6pm to 1130pm(Mon-Sun)                       9
930am to 1am(Mon-Sun)                                      9
12noon to 4pm,630pm to 12midnight(Mon-Sun)                 9
11am to 330am(Mon-Sun)                                     8
1130am to 330pm,7pm to 11pm(Mon-Sun)                       8
9am to 930pm(Mon-Sun)                                      8
11am to 330pm,6pm to 1130pm(Mon-Sun)                       8
930am to 9pm(Mon-Sun)                                      8
10am to 10pm(Mon-Sat),Closed(Sun)                          8
11am to 3pm,6pm to 1130pm(Mon-Sun)                         8
4pm to 1130pm(Mon-Sun)                                     8
11am to 330pm,630pm to 11pm(Mon-Sun)                       8
830am to 930pm(Mon-Sun)                                    8
1130am to 3pm,7pm to 11pm(Mon-Sun)                         8
5pm to 2am(Mon-Sun)                                        8
7am to 130am(Mon-Sun)                                      8
1130am to 3pm,7pm to 1130pm(Mon-Sun)                       8
12noon to 3pm,7pm to 1230AM(Mon-Sun)                       8
3pm to 12midnight(Mon-Sun)                                 8
1130am to 3am(Mon-Sun)                                     8
11am to 330pm,6pm to 11pm(Mon-Sun)                         7
12midnight to 1am,12noon to 12midnight(Mon-Sun)            7
1130am to 4pm,630pm to 12midnight(Mon-Sun)                 7
11am to 5am(Mon-Sun)                                       7
8am to 7pm(Mon-Sun)                                        7
10am to 4am(Mon-Sun)                                       7
1130am to 330pm,7pm to 1230AM(Mon-Sun)                     7
1130am to 1145pm(Mon-Sun)                                  7
12noon to 330pm,630pm to 1230AM(Mon-Sun)                   7
11am to 11pm(Mon-Sat),Closed(Sun)                          7
2pm to 1am(Mon-Sun)                                        7
Closed(Mon),10am to 10pm(Tue-Sun)                          7
430pm to 12midnight(Mon-Sun)                               7
4pm to 4am(Mon-Sun)                                        7
1pm to 3am(Mon-Sun)                                        7
12noon to 4pm,7pm to 3am(Mon-Sun)                          7
7am to 930pm(Mon-Sun)                                      7
12noon to 330am(Mon-Sun)                                   7
5am to 1am(Mon-Sun)                                        7
830am to 830pm(Mon-Sun)                                    7
12noon to 4pm,6pm to 1130pm(Mon-Sun)                       7
6pm to 2am(Mon-Sun)                                        7
9am to 2am(Mon-Sun)                                        7
7am to 7pm(Mon-Sun)                                        7
12noon to 330pm,6pm to 11pm(Mon-Sun)                       7
10am to 2am(Mon-Sun)                                       7
11am to 1245AM(Mon-Sun)                                    6
11am to 4pm,630pm to 11pm(Mon-Sun)                         6
11am to 3pm,630pm to 12midnight(Mon-Sun)                   6
11am to 1215AM(Mon-Sun)                                    6
1130am to 3pm,630pm to 11pm(Mon-Sun)                       6
10am to 9pm(Mon-Sat),Closed(Sun)                           6
12noon to 8pm(Mon-Sun)                                     6
1230pm to 330pm,7pm to 1130pm(Mon-Sun)                     6
130pm to 12midnight(Mon-Sun)                               6
1230pm to 330pm,7pm to 12midnight(Mon-Sun)                 6
1130am to 3pm,6pm to 11pm(Mon-Sun)                         6
630am to 1130pm(Mon-Sun)                                   6
1130am to 330pm,6pm to 12midnight(Mon-Sun)                 6
1130am to 330pm,730pm to 1130pm(Mon-Sun)                   6
11am to 7pm(Mon-Sat),Closed(Sun)                           6
1130am to 2am(Mon-Sun)                                     6
9am to 830pm(Mon-Sun)                                      6
6am to 1230AM(Mon-Sun)                                     6
12noon to 1145pm(Mon-Sun)                                  6
2pm to 10pm(Mon-Sun)                                       6
10am to 1145pm(Mon-Sun)                                    6
12noon to 330pm,6pm to 1130pm(Mon-Sun)                     6
7am to 8pm(Mon-Sun)                                        6
1pm to 2am(Mon-Sun)                                        6
1030am to 630pm(Mon-Sun)                                   6
830am to 9pm(Mon-Sun)                                      6
3pm to 1am(Mon-Sun)                                        6
11am to 830pm(Mon-Sun)                                     6
11am to 330pm,6pm to 1230AM(Mon-Sun)                       5
9am to 1145pm(Mon-Sun)                                     5
130pm to 130am(Mon-Sun)                                    5
6pm to 1230AM(Mon-Sun)                                     5
11am to 12noon(Mon-Sun)                                    5
11am to 11pm(Mon,Wed,Thu,Fri,Sat,Sun),Closed...            5
12noon to 9pm(Mon-Sun)                                     5
630am to 12midnight(Mon-Sun)                               5
11am to 5pm(Mon-Sun)                                       5
10am to 6pm(Mon-Sat),Closed(Sun)                           5
11am to 12midnight(Mon-Thu),12midnight to ...              5
5am to 12midnight(Mon-Sun)                                 5
11am to 3pm,6pm to 10pm(Mon-Sun)                           5
1130am to 330pm,730pm to 12midnight(Mon-Sun)               5
12noon to 330pm,7pm to 4am(Mon-Sun)                        5
11am to 4pm,7pm to 1145pm(Mon-Sun)                         5
Closed(Mon),1130am to 1130pm(Tue-Sun)                      5
1pm to 1230AM(Mon-Sun)                                     5
7pm to 1130pm(Mon-Sun)                                     5
6am to 1030pm(Mon-Sun)                                     5
12noon to 4pm,730pm to 1130pm(Mon-Sun)                     5
10am to 830pm(Mon-Sun)                                     5
12noon to 4pm,6pm to 11pm(Mon-Sun)                         5
6pm to 130am(Mon-Sun)                                      5
7am to 5am(Mon-Sun)                                        5
1pm to 10pm(Mon-Sun)                                       5
Closed(Mon),11am to 12midnight(Tue-Sun)                    5
8am to 6pm(Mon-Sun)                                        5
130pm to 11pm(Mon-Sun)                                     5
11am to 10pm(Mon-Sat),Closed(Sun)                          5
12noon to 4pm,7pm to 2am(Mon-Sun)                          5
Closed(Mon),11am to 10pm(Tue-Sun)                          5
7pm to 1am(Mon-Sun)                                        5
12noon to 330pm,7pm to 1030pm(Mon-Sun)                     5
8am to 4am(Mon-Sun)                                        5
8am to 8pm(Mon-Sat),Closed(Sun)                            4
9am to 12midnight(Mon,Tue,Wed,Thu,Sat,Sun)...              4
11am to 3pm,630pm to 1130pm(Mon-Sun)                       4
1130am to 4pm,7pm to 11pm(Mon-Sun)                         4
12noon to 12midnight(Mon,Tue,Wed,Thu,Sun)...               4
5pm to 1am(Mon-Sun)                                        4
2pm to 2am(Mon-Sun)                                        4
Closed(Mon),1230pm to 11pm(Tue-Sun)                        4
Closed(Mon),11am to 330pm,7pm to 1130pm(Tue-Sun)           4
830am to 1230AM(Mon-Sun)                                   4
5am to 10pm(Mon-Sun)                                       4
1130am to 4pm,630pm to 1am(Mon-Sun)                        4
930am to 130am(Mon-Sun)                                    4
1130am to 4pm,7pm to 1230AM(Mon-Sun)                       4
630pm to 1230AM(Mon-Sun)                                   4
11am to 4pm,7pm to 1am(Mon-Sun)                            4

In [ ]:
#Splitting the TIMING column and storing it in different columns

In [63]:
temp_df=raw_df["TIMING"].str.split("(",n=1,expand=True)
temp_df

                                                      0  \
0                                       12noon to 130am
1                                            2pm to 1am
2                                         12noon to 1am
3                                       12noon to 130am
4                                         1130am to 1am
5                                         12noon to 1am
6                                           10am to 3am
7                                       12noon to 130am
8                                           11am to 1am
9                                         12noon to 1am
10                                        12noon to 1am
11                                        12noon to 1am
12                                           9am to 1am
13                                        1130am to 5am
14                                      12noon to 130am
16                                       730am to 130am
17                             12noon to 4pm,7pm to 4am
18                                        8am to 1230AM
19                                     12noon to 1230AM
20                                        12noon to 1am
21                                               Closed
22                                          10am to 4am
23                          12noon to 3pm,7pm to 1230AM
24                                      12noon to 130am
25                                        10am to 130am
26                                     12noon to 1230AM
27                                          11am to 1am
28                                          11am to 1am
29                                        12noon to 1am
30                                      12noon to 130am
32                                     1030am to 1230AM
33                                         4pm to 230am
34                                          11am to 3am
35                         12noon to 330pm,430pm to 2am
36                           12noon to 330pm,7pm to 3am
37          12midnight to 130am,12noon to 12midnight...
38                                       11am to 1230AM
39                                     12noon to 1230AM
40                         12noon to 330pm,7pm to 330am
41                                       10am to 1230AM
42                                           1pm to 1am
43                                 12noon to 12midnight
44                                 12noon to 12midnight
45                                          7am to 11pm
46                                      530pm to 1130pm
48                                       12noon to 11pm
49                                 1030am to 12midnight
50                                     1130am to 1145pm
51                                          7am to 11pm
52                                         10am to 11pm
53                                       12noon to 11pm
54                                    8am to 12midnight
55                      12noon to 3pm,6pm to 12midnight
56                                        9am to 1145pm
57                                     12noon to 1030pm
58               1150am to 330pm,630pm to 12midnight...
59                                 12noon to 12midnight
60                                          9am to 10pm
61         7am to 10am,1230pm to 330pm,7pm to 1130pm...
62                                    8am to 12midnight
64                                        9am to 1130pm
65                                      930am to 1130pm
66                                 12noon to 12midnight
67                                       12noon to 11pm
68                                       12noon to 11pm
69                          12noon to 330pm,7pm to 11pm
70                                   11am to 12midnight
71                        12noon to 330pm,7pm to 1115pm
72                                    9am to 12midnight
73                                        830am to 11pm
74                                         11am to 11pm
75                                        830am to 11pm
76                                     1130am to 1130pm
77                                   11am to 12midnight
78                        1130am to 3pm,645pm to 1245AM
80                           12noon to 4pm,7pm to 145am
81                          11am to 330pm,6pm to 1245AM
82                                     12noon to 1245AM
83                             12noon to 4pm,8pm to 1am
84                                           4pm to 1am
85                                     1130am to 1230AM
86                            10am to 3pm,6pm to 1230AM
87               12midnight to 1am,12noon to 12midnight
88                                     1130am to 1250AM
89                                       11am to 1230AM
90                                      1030am to 130am
91                                     1030am to 1230AM
92                                     12noon to 1230AM
93                                          10am to 3am
94                                          11am to 1am
96                               11am to 3pm,6pm to 3am
97                                      12noon to 130am
98                                           1pm to 1am
99                         12noon to 4pm,630pm to 130am
100                                          8pm to 4am
101                          1130am to 4pm,630pm to 1am
102                                         10am to 3am
103                          12noon to 330pm,7pm to 6am
104                                       12noon to 1am
105                                       12noon to 4am
106                    1130am to 330pm,7pm to 1130pm...
107                       12noon to 330pm,7pm to 1230AM
108                                          7pm to 4am
109                                       12noon to 2am
110                1145am to 4pm,645pm to 12midnight...
112                                        8am to 130am
113                                         11am to 1am
114                 12midnight to 3am,6pm to 12midnight
115                                    1030am to 1230AM
116                                        7pm to 330am
117                                     12noon to 130am
118                                       1130am to 1am
119                                12noon to 12midnight
120                         11am to 330pm,6pm to 1130pm
121                                      11am to 1130pm
122                                              Closed
123                                         9am to 11pm
124                                      1130am to 11pm
125                                       5pm to 1130pm
126                                    12noon to 1130pm
128                                        10am to 11pm
129                                       8am to 1130pm
130                     1130am to 4pm,7pm to 12midnight
131                                       11am to 930pm
132                                         6am to 10pm
133                                   6am to 12midnight
134                                 930am to 12midnight
135                                12noon to 12midnight
136                                        11am to 11pm
137                                12noon to 12midnight
138                                              Closed
139                                12noon to 12midnight
140                                        11am to 11pm
141                                              Closed
142                                         8am to 11pm
144                                         7am to 11pm
145                                  10am to 12midnight
146                                  11am to 12midnight
147                                12noon to 12midnight
148                                        10am to 11pm
149                                    12noon to 1130pm
150                                     810am to 1140pm
151                                      11am to 1130pm
152                                      10am to 1130pm
153                                    1130am to 1130pm
154                                     830am to 1130pm
155                                 929am to 12midnight
156                                         10am to 8pm
157                                      11am to 1130pm
158                       1130am to 330pm,7pm to 1130pm
160                                          9pm to 5am
161                       1230pm to 345pm,6pm to 1230AM
162                                      11am to 1230AM
163                                         11am to 1am
164                                      530pm to 130am
165                                       8am to 1230AM
166                                       6pm to 1230AM
167                                    1130am to 1230AM
168                                       11am to 330am
169                         11am to 330pm,7pm to 1230AM
170                                         10am to 2am
171                                         11am to 1am
172                                         11am to 1am
173                                       10am to 130am
174                                    12noon to 1230AM
176                                      11am to 1230AM
177                                   8pm to 12midnight
178                            12noon to 3pm,7pm to 2am
179                                       1130am to 4am
180                                         11am to 2am
181                                         11am to 5am
182                                       12noon to 1am
183                                          2pm to 2am
184                                       1130am to 1am
185                                     1130am to 130am
186                                          8am to 1am
187                                    12noon to 1230AM
188                                       12noon to 1am
189                           11am to 5pm,7pm to 1230AM
190                           11am to 4pm,7pm to 1215AM
192                                       11am to 230am
193                                        7pm to 130am
194                                       12noon to 1am
195                                         11am to 1am
196                                          8am to 1am
197                          12noon to 330pm,7pm to 1am
198                                       1030am to 2am
199                         1030am to 4pm,7pm to 1230AM
200                                       12noon to 1am
201                                       11am to 130am
202                        1145am to 330pm,645pm to 1am
203                                     12noon to 130am
204                       12noon to 4pm,630pm to 1230AM
205                                       12noon to 1am
206                                    1130am to 1230AM
208                                         10am to 4am
209                                         11am to 1am
210                                       10am to 130am
211                               1pm to 3pm,6pm to 1am
212                                         11am to 2am
213                                      10am to 1230AM
214                                         11am to 1am
215                                      10am to 1230AM
216                                      730am to 130am
217                                       12noon to 1am
218                                       1130am to 1am
219                     1230pm to 430pm,730pm to 1230AM
220                                       12noon to 1am
221                                          7pm to 4am
222                                         11am to 1am
224                                    12noon to 1230AM
225                                       1130am to 4am
226                                       6pm to 1230AM
227                                 830am to 12midnight
228                                       8am to 1030pm
229                                              Closed
230                           1130am to 3pm,7pm to 11pm
231                     1230pm to 330pm,730pm to 1130pm
232                                         10am to 2am
233                   12noon to 330pm,7pm to 12midnight
234                     1130am to 4pm,7pm to 12midnight
235                                    1130am to 1130pm
236                                              Closed
237                                      11am to 1130pm
238                       12noon to 330pm,7pm to 1130pm
240                       12noon to 330pm,7pm to 1130pm
241                                   9am to 12midnight
242                                              Closed
243                                         9am to 11pm
244                                              Closed
245                      730am to 330pm,730pm to 1030pm
246                                        11am to 11pm
247                                12noon to 12midnight
248                                        11am to 11pm
249                                  11am to 12midnight
250                           1230pm to 4pm,5pm to 11pm
251                                  11am to 12midnight
252                       12noon to 330pm,7pm to 1130pm
253                                    1130am to 1130pm
254                           12noon to 4pm,7pm to 11pm
256                       12noon to 4pm,645pm to 1150pm
257                                        11am to 11pm
258                                        11am to 11pm
259                                        10am to 10pm
260                                      12noon to 11pm
261                                   8am to 12midnight
262                                      430pm to 930pm
263                                   6am to 12midnight
264                                  11am to 12midnight
265                         11am to 415pm,7pm to 1145pm
266                                         7am to 11pm
267                         12noon to 3pm,7pm to 1230AM
268                                       730am to 11pm
269                                  11am to 12midnight
270                                       11am to 930pm
272                                    1130am to 1130pm
273                                  11am to 12midnight
274                                        11am to 11pm
275                                              Closed
276                                    1130am to 1130pm
277                                          9am to 9pm
278                       12noon to 330pm,7pm to 1130pm
279                   12noon to 330pm,7pm to 12midnight
280                                12noon to 12midnight
281                           1130am to 3pm,7pm to 11pm
282                                  11am to 12midnight
283                                       8am to 1030pm
284                                  11am to 12midnight
285                       11am to 5pm,7pm to 12midnight
286                     12noon to 330pm,630pm to 1130pm
288                             11am to 4pm,7pm to 11pm
289                                     930am to 1130pm
290                                   8am to 12midnight
291                                         11am to 1am
292                                          7pm to 4am
293                                      11am to 1230AM
294                           11am to 4pm,7pm to 1230AM
295                         12noon to 3pm,6pm to 1230AM
296                                     830am to 1230AM
297                                    1030am to 1230AM
298                                    1030am to 1230AM
299                                         11am to 1am
300                           11am to 4pm,7pm to 1230AM
301                                          6pm to 4am
302                                        730am to 1am
304                                          1pm to 1am
305                                      10am to 1230AM
306                                    1030am to 1230AM
307                                     930am to 1230AM
308                                       10am to 130am
309                                       11am to 130am
310                                      11am to 1230AM
311              12midnight to 115am,11am to 12midnight
312                                         11am to 1am
313                                          8am to 4am
314                                          6pm to 4am
315                12midnight to 1am,11am to 12midnight
316                                       12noon to 1am
317                                       11am to 130am
318                                          1pm to 1am
320                          1145am to 4pm,745pm to 3am
321                                         11am to 5am
322                                       5pm to 1230AM
323                                          6am to 4am
324                         11am to 330pm,7pm to 1230AM
325                                       11am to 130am
326                                         11am to 3am
327                                          8am to 2am
328                                      11am to 1230AM
329                                          9am to 1am
330                               1pm to 4pm,6pm to 1am
331                                        930am to 2am
332                                      10am to 1230AM
333                                      11am to 1230AM
334                                    1230pm to 1230AM
336                                   7am to 12midnight
337                     12noon to 3pm,7pm to 12midnight
338                                              Closed
339                                    1130am to 1130pm
340                       1130am to 330pm,730pm to 11pm
341       12noon to 4pm,4pm to 7pm,7pm to 12midnight...
342                                12noon to 12midnight
343                                   9am to 12midnight
344                                     730am to 1145pm
345                                        11am to 11pm
346                                    12noon to 1130pm
347                                      11am to 1130pm
348                                    1030am to 1130pm
349                                  10am to 12midnight
350                         12noon to 3pm,7pm to 1130pm
352                     12noon to 345pm,630pm to 1130pm
353                                12noon to 12midnight
354                                         9am to 10pm
355                                         8am to 10pm
356                                    12noon to 1130pm
357                     1130am to 4pm,7pm to 12midnight
358                                    1130am to 1230AM
359                       1130am to 4pm,630pm to 1130pm
360                                    1130am to 1130pm
361                       1130am to 330pm,7pm to 1145pm
362                                     930am to 1030pm
363                                        11am to 10pm
364                                       9am to 1130pm
365                                1030am to 12midnight
366                       12noon to 330pm,7pm to 1130pm
368                                       12noon to 1am
369                         12noon to 3pm,7pm to 1230AM
370                                         11am to 3am
371                                   9am to 12midnight
372                                12noon to 12midnight
373                                       12noon to 1am
374                          12noon to 3pm,7pm to 130am
375                                       9am to 1230AM
376                                        730am to 5am
377                                     12noon to 130am
378                          1230pm to 4pm,7pm to 130am

In [65]:
##Assigning the columns back to raw_df
raw_df["TIMING"]=temp_df[0]
raw_df['DAYS_OPEN']=temp_df[1]
raw_df.head()

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Biryani,Continental,American,Fast Food",First International Financial Centre-- Bandra Kurla Complex,Casual Dining,12noon to 130am,Excellent,4.9,3529,Mon-Sun)
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723,Mon-Sun)
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337,Mon-Sun)
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am,Very Good,4.3,1200,Mon-Sun)
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am,Veľmi dobré,4.4,5995,Mon-Sun)

In [68]:
raw_df["DAYS_OPEN"]=raw_df["DAYS_OPEN"].str.replace(")","",regex=False)

In [69]:
raw_df["DAYS_OPEN"]

0                                            Mon-Sun
1                                            Mon-Sun
2                                            Mon-Sun
3                                            Mon-Sun
4                                            Mon-Sun
5                                            Mon-Sun
6                                            Mon-Sun
7                                            Mon-Sun
8                                            Mon-Sun
9                                            Mon-Sun
10                                           Mon-Sun
11                                           Mon-Sun
12                          Mon,9am to 130am(Tue-Sun
13                    Mon,1130am to 130am(Tue,Wed...
14                                           Mon-Sun
16                                           Mon-Sun
17                                           Mon-Sun
18                                           Mon-Sun
19                                           Mon-Sun
20                                           Mon-Sun
21                       Mon,12noon to 130am(Tue-Sun
22                                           Mon-Sun
23                                           Mon-Sun
24                     Mon-Fri,12noon to 3am(Sat-Sun
25                                           Mon-Sun
26                                           Mon-Sun
27                                           Mon-Sun
28                                           Mon-Sun
29                                           Mon-Sun
30                                           Mon-Sun
32                                           Mon-Sun
33                                           Mon-Sun
34                                           Mon-Sun
35                                           Mon-Sun
36                                           Mon-Sun
37                                              None
38                                           Mon-Sun
39                                           Mon-Sun
40                                    Mon,Tue,Wed...
41                                           Mon-Sun
42                                           Mon-Sun
43                                           Mon-Sun
44                                           Mon-Sun
45                                           Mon-Sun
46                                           Mon-Sun
48                  Mon-Thu,12noon to 1130pm(Fri-Sun
49                                           Mon-Sun
50                                           Mon-Sun
51                                           Mon-Sun
52                                           Mon-Sun
53                                           Mon-Sun
54                                           Mon-Sun
55                                           Mon-Sun
56                                           Mon-Sun
57                    Mon-Thu,12noon to 11pm(Fri-Sun
58                                              None
59                                           Mon-Sun
60                                           Mon-Sun
61                                              None
62                                           Mon-Sun
64                                           Mon-Sun
65                        Mon-Thu,930am to 1152pm...
66                                           Mon-Sun
67                                           Mon-Sun
68                  Mon-Thu,12noon to 1130pm(Fri-Sun
69                                           Mon-Sun
70                                           Mon-Sun
71                                           Mon-Sun
72                                           Mon-Sun
73                    Mon-Fri,830am to 12midnight...
74                                           Mon-Sun
75                Mon-Sat,11am to 4pm,7pm to 11pm...
76                                           Mon-Sun
77                                           Mon-Sun
78                                           Mon-Sun
80                                           Mon-Sun
81                                           Mon-Sun
82                                           Mon-Sun
83                                           Mon-Sun
84                                           Mon-Sun
85                                           Mon-Sun
86                                           Mon-Sun
87                                           Mon-Sun
88                                           Mon-Sun
89                                           Mon-Sun
90                                           Mon-Sun
91                                           Mon-Sun
92                                           Mon-Sun
93                                           Mon-Sun
94                                           Mon-Sun
96                            Mon-Fri,11am to 3am...
97                                           Mon-Sun
98                                           Mon-Sun
99                                           Mon-Sun
100                                          Mon-Sun
101                                          Mon-Sun
102                                          Mon-Sun
103                                          Mon-Sun
104                    Mon-Thu,12noon to 2am(Fri-Sun
105                                          Mon-Sun
106                                             None
107                                          Mon-Sun
108              Mon-Fri,12noon to 4pm,5pm to 4am...
109                                          Mon-Sun
110                                             None
112                                          Mon-Sun
113                                          Mon-Sun
114                                       Mon,Wed...
115                                          Mon-Sun
116                                          Mon-Sun
117                  Mon-Tue,12noon to 230am(Wed-Sun
118                                          Mon-Sun
119                                          Mon-Sun
120                                          Mon-Sun
121                                          Mon-Sun
122                        Mon,7am to 1030pm(Tue-Sun
123                          Mon-Sat,3pm to 11pm(Sun
124                                          Mon-Sun
125                        Mon,1pm to 1130pm(Tue-Sun
126                      Mon-Fri,12noon to 1230AM...
128                          Mon,8am to 11pm(Tue-Sun
129                                          Mon-Sun
130                                          Mon-Sun
131                                          Mon-Sun
132                                          Mon-Sun
133                                          Mon-Sun
134                                          Mon-Sun
135                                          Mon-Sun
136                                          Mon-Sun
137                                          Mon-Sun
138                    Mon,4pm to 12midnight(Tue-Sun
139                         Mon-Fri,12noon to 1am...
140                                          Mon-Sun
141                         Mon,9am to 930pm(Tue-Sun
142               Mon,Tue,Fri,Sat,Sun,6pm to 11pm...
144                                          Mon-Sun
145                                          Mon-Sun
146                                          Mon-Sun
147                                          Mon-Sun
148                                          Mon-Sun
149                  Mon-Thu,12noon to 12midnight...
150                         Mon-Tue,8pm to 1140pm...
151                                          Mon-Sun
152                                          Mon-Sun
153                                          Mon-Sun
154                                          Mon-Sun
155                       Mon,930am to 12midnight...
156                                          Mon-Sun
157                                          Mon-Sun
158                                          Mon-Sun
160                                          Mon-Sun
161                                          Mon-Sun
162                                          Mon-Sun
163                                          Mon-Sun
164                                          Mon-Sun
165                                          Mon-Sun
166                                          Mon-Sun
167                                          Mon-Sun
168                                          Mon-Sun
169                                          Mon-Sun
170                                          Mon-Sun
171                                          Mon-Sun
172                                          Mon-Sun
173                                          Mon-Sun
174                                          Mon-Sun
176                                          Mon-Sun
177                 Mon-Tue,12midnight to 4am,8pm...
178                                          Mon-Sun
179                                          Mon-Sun
180                                          Mon-Sun
181                                          Mon-Sun
182                                          Mon-Sun
183                                          Mon-Sun
184                                          Mon-Sun
185                                          Mon-Sun
186                Mon,Tue,Wed,Thu,Sun,8am to 3am...
187                                          Mon-Sun
188                                          Mon-Sun
189                                          Mon-Sun
190                                          Mon-Sun
192                                          Mon-Sun
193                 Mon-Fri,12noon to 4pm,7pm to ...
194                                          Mon-Sun
195                                          Mon-Sun
196                                          Mon-Sun
197                                          Mon-Sun
198                                          Mon-Sun
199                                          Mon-Sun
200                                          Mon-Sun
201                     Mon-Fri,9am to 130am(Sat-Sun
202                                          Mon-Sun
203                                          Mon-Sun
204                                          Mon-Sun
205                                          Mon-Sun
206                                          Mon-Sun
208                                          Mon-Sun
209                                          Mon-Sun
210                                          Mon-Sun
211                                          Mon-Sun
212                                          Mon-Sun
213                                          Mon-Sun
214                                          Mon-Sun
215                                          Mon-Sun
216                                          Mon-Sun
217                                          Mon-Sun
218                                          Mon-Sun
219                                          Mon-Sun
220                                          Mon-Sun
221              Mon-Fri,12noon to 4pm,7pm to 4am...
222                                          Mon-Sun
224                                          Mon-Sun
225                                          Mon-Sun
226                                          Mon-Sun
227                                          Mon-Sun
228                                          Mon-Sun
229          Mon,11am to 330pm,7pm to 1130pm(Tue-Sun
230                                          Mon-Sun
231                                          Mon-Sun
232                   Mon,10am to 12midnight(Tue-Sun
233                                          Mon-Sun
234                                          Mon-Sun
235                                          Mon-Sun
236      Mon,1pm to 12midnight(Tue-Sat,12noon to ...
237                                          Mon-Sun
238                                          Mon-Sun
240                                          Mon-Sun
241                                          Mon-Sun
242                        Mon,7am to 1030pm(Tue-Sun
243                                          Mon-Sun
244                         Mon,10am to 10pm(Tue-Sun
245                                          Mon-Sun
246                                          Mon-Sun
247                                          Mon-Sun
248                                          Mon-Sun
249                                          Mon-Sun
250                                   Mon,Tue,Thu...
251                                          Mon-Sun
252                                          Mon-Sun
253                                          Mon-Sun
254                                          Mon-Sun
256                                          Mon-Sun
257                                          Mon-Sun
258                                          Mon-Sun
259                Mon,Tue,Wed,Fri,Sat,Sun,Closed...
260                                          Mon-Sun
261                                          Mon-Sun
262                                          Mon-Sun
263                                          Mon-Sun
264                                          Mon-Sun
265                                          Mon-Sun
266                                          Mon-Sun
267                                          Mon-Sun
268                                          Mon-Sun
269                                          Mon-Sun
270                               Mon-Sat,Closed(Sun
272                                          Mon-Sun
273                                          Mon-Sun
274                                          Mon-Sun
275                        Mon,8am to 1030pm(Tue-Sun
276                                          Mon-Sun
277                           Mon-Sat,9am to 8pm(Sun
278                                          Mon-Sun
279                                          Mon-Sun
280                                          Mon-Sun
281                                          Mon-Sun
282                                          Mon-Sun
283                                          Mon-Sun
284                                          Mon-Sun
285                                          Mon-Sun
286                                          Mon-Sun
288                                          Mon-Sun
289                                          Mon-Sun
290                                          Mon-Sun
291                                          Mon-Sun
292                                          Mon-Sun
293                                          Mon-Sun
294                                          Mon-Sun
295                                          Mon-Sun
296                                          Mon-Sun
297                                          Mon-Sun
298                                          Mon-Sun
299                                          Mon-Sun
300                               Mon-Sat,7pm to ...
301                                          Mon-Sun
302                       Mon,Tue,Wed,Thu,Sat,Sun...
304                                          Mon-Sun
305                                          Mon-Sun
306                                          Mon-Sun
307                                          Mon-Sun
308                                          Mon-Sun
309                                          Mon-Sun
310                                          Mon-Sun
311                                          Mon-Sun
312                                          Mon-Sun
313                                          Mon-Sun
314                                          Mon-Sun
315                                          Mon-Sun
316                                          Mon-Sun
317                                          Mon-Sun
318                                          Mon-Sun
320                                          Mon-Sun
321                                          Mon-Sun
322                                          Mon-Sun
323                 Mon,Tue,Wed,Fri,Sun,630am to ...
324                                          Mon-Sun
325                                          Mon-Sun
326                                          Mon-Sun
327                                          Mon-Sun
328                                          Mon-Sun
329                                          Mon-Sun
330                                          Mon-Sun
331                                          Mon-Sun
332                                          Mon-Sun
333                                          Mon-Sun
334                                          Mon-Sun
336                                          Mon-Sun
337                                          Mon-Sun
338             Mon,1130am to 330pm,630pm to 11pm...
339                                          Mon-Sun
340                                       Mon,Wed...
341                                             None
342                                          Mon-Sun
343                                          Mon-Sun
344                                          Mon-Sun
345                                          Mon-Sun
346                       Mon,Wed,Thu,Fri,Sat,Sun...
347                                          Mon-Sun
348                                          Mon-Sun
349                                          Mon-Sun
350                                          Mon-Sun
352                                          Mon-Sun
353                                          Mon-Sun
354                                          Mon-Sun
355                    Mon,8am to 12midnight(Tue-Sun
356                                          Mon-Sun
357                                          Mon-Sun
358                                          Mon-Sun
359                                          Mon-Sun
360                                          Mon-Sun
361                                          Mon-Sun
362                                          Mon-Sun
363                                          Mon-Sun
364                                          Mon-Sun
365                                          Mon-Sun
366                                          Mon-Sun
368                                          Mon-Sun
369                                          Mon-Sun
370                                          Mon-Sun
371                       Mon,Tue,Wed,Sun,9am to ...
372                     Mon-Thu,12noon to 1am(Fri...
373                                          Mon-Sun
374                                          Mon-Sun
375                       Mon,Tue,Wed,Fri,Sat,Sun...
376                                          Mon-Sun
377                                          Mon-Sun
378                                          Mon-Sun
379                                          Mon-Sun
380                                          Mon-Sun
381                                          Mon-Sun
382                                          Mon-Sun
384                                          Mon-Sun
385                                          Mon-Sun
386                                          Mon-Sun
387                                          Mon-Sun
388                                          Mon-Sun
389                                          Mon-Sun
390                                          Mon-Sun
391                                          Mon-Sun
392                                          Mon-Sun
393                     Mon-Fri,11am to 11pm(Sat-Sun
394                                          Mon-Sun
395                                          Mon-Sun
396               Mon,8am to 11pm(Tue-Fri,8am to ...
397                                          Mon-Sun
398                                          Mon-Sun
400                                          Mon-Sun
401                                          Mon-Sun

In [78]:
raw_df[raw_df["DAYS_OPEN"]!="Mon-Sun"]["DAYS_OPEN"].value_counts()

Mon-Sat,Closed(Sun                             170
Mon,11am to 11pm(Tue-Sun                        30
Mon,Wed,Thu,Fri,Sat,Sun...                      26
Mon,Tue,Wed...                                  25
Mon,Tue,Wed,Thu,Sat,Sun...                      23
Mon,Tue...                                      16
Mon,12noon to 11pm(Tue-Sun                      15
Mon,Wed,Thu,Fri,Sat,Sun,Closed...               13
Mon,Wed,Thu,Fri...                              11
Mon,Tue,Wed,Thu...                              11
Mon,Tue,Wed,Fri,Sat,Sun...                      10
Mon-Sat,(Sun                                    10
Mon,Tue,Wed,Fri,Sat,Sun,Closed...               10
Mon,Tue,Wed,Thu,Fri,Sun...                      10
Mon-Fri,Closed(Sat-Sun                          10
Mon,Wed...                                       9
Mon,11am to 12midnight(Tue-Sun                   8
Mon...                                           8
Mon,10am to 10pm(Tue-Sun                         8
Mon,Tue,Wed,Thu,Sun...                           8
Mon-Thu,12noon to ...                            7
Mon,Wed,Thu...                                   7
Mon-Fri,11am to 12midnight(Sat-Sun               6
Mon,Tue,Thu,Fri,Sat,Sun,Closed...                6
Mon,Tue,Wed,Fri,Sat...                           6
Mon,Wed,Thu,Fri,Sat...                           6
Mon,Tue,Thu...                                   6
Mon,11am to 10pm(Tue-Sun                         6
Mon,8am to 11pm(Tue-Sun                          6
Mon,1230pm to 11pm(Tue-Sun                       6
Mon,12noon to 1130pm(Tue-Sun                     6
Mon,Tue,Thu,Fri,Sat,Sun...                       6
Mon-Sat,11am to 11pm(Sun                         5
Mon,12noon...                                    5
Mon-Thu,12midnight to ...                        5
Mon,1130am to 1130pm(Tue-Sun                     5
Mon-Thu,12noon...                                5
Mon,Tue,Wed,Thu,Sat...                           5
Mon-Sat,7pm to ...                               4
Mon,Tue,Wed,Thu,Fri...                           4
Mon-Fri,11am to ...                              4
Mon,Tue,Wed,Thu,Sun,11am to ...                  4
Mon,Tue,Wed,Fri...                               4
Mon,12noon to 330pm,7pm to ...                   4
Mon,11am to 3pm,7pm to 11pm(Tue-Sun              4
Mon,1130am...                                    4
Mon,11am to 330pm,7pm to 1130pm(Tue-Sun          4
Mon-Sat,3pm to 11pm(Sun                          4
Mon,8am to 12midnight(Tue-Sun                    4
Mon,830am to 10pm(Tue-Sun                        4
Mon,12noon to ...                                4
Mon-Thu,7am to 1145pm(Fri-Sun                    4
Mon-Sat,5pm to 11pm(Sun                          4
Mon-Fri,11am to 130am(Sat-Sun                    4
Mon,1130am to 330pm,7pm to 1130pm...             4
Mon-Sat,11am to 12midnight(Sun                   4
Mon-Fri,12noon...                                4
Mon-Tue,12noon to 4am(Wed-Sun                    4
Mon-Thu,1130am to 12midnight...                  4
Mon-Sat,5pm to 10pm(Sun                          3
Mon-Fri,8am to 11pm(Sat-Sun                      3
Mon-Sat,12noon to 1am(Sun                        3
Mon-Thu,11am to 12midnight(Fri-Sun               3
Mon,12noon to 12midnight...                      3
Mon,10am to 1030pm(Tue-Sun                       3
Mon,1130am to 3pm,630pm to 11pm(Tue-Sun          3
Mon-Sat,12noon to 10pm(Sun                       3
Mon-Thu,12noon to 12midnight...                  3
Mon-Sat,6pm to 11pm(Sun                          3
Mon,10am to 12midnight(Tue-Sun                   3
Mon,4pm to 11pm(Tue-Sun                          3
Mon,Tue,Wed,Thu,Fri,Sun,11am...                  3
Mon,9am to 1130pm(Tue-Sun                        3
Mon-Sat,11am to ...                              3
Mon-Thu,11am to ...                              3
Mon,Tue,Wed,Thu,Sat,Sun,Closed...                3
Mon,12noon to 3pm,7pm to 12midnight...           3
Mon-Sat,11am...                                  3
Mon,10am to 11pm(Tue-Sun                         3
Mon-Fri,12noon to ...                            3
Mon,6pm to 130am(Tue-Sun                         3
Mon,1pm to 10pm(Tue-Sun                          3
Mon,12noon to 3pm,8pm to 11pm(Tue-Sun            3
Mon-Sat,4pm to 10pm(Sun                          3
Mon,12noon to 130am(Tue-Sun                      3
Mon-Sat,10am to 12midnight(Sun                   3
Mon-Fri,830am to 12midnight...                   3
Mon,11am to 1030pm(Tue-Sun                       3
Mon,1130am to 330pm,730pm to 1130pm...           3
Mon,11am to 330pm,7pm to ...                     3
Mon-Sat,2pm to 10pm(Sun                          3
Mon-Sat,11am to 10pm(Sun                         3
Mon,10am to 8pm(Tue-Sun                          3
Mon-Thu,12noon to 1130pm(Fri-Sun                 3
Mon,11am to 8pm(Tue-Sun                          3
Mon,Tue,Wed,Thu,Sat,Sun,2pm...                   3
Mon-Fri,12noon to 1am(Sat-Sun                    3
Mon,12noon to 12midnight(Tue-Sun                 3
Mon-Tue,11am to 11pm(Wed-Sun                     3
Mon,Tue,Wed,Thu,Sun,12noon to ...                3
Mon,Tue,Thu,Fri...                               3
Mon-Thu,12noon to 11pm(Fri-Sun                   2
Mon-Fri,12noon to 1am...                         2
Mon,11am to 3pm,6pm to 10pm(Tue-Sun              2
Mon,9am to 130am(Tue-Sun                         2
Mon-Sat,12noon to 12midnight...                  2
Mon-Fri,12noon to 11pm(Sat-Sun                   2
Mon,7am to 9pm(Tue-Sun                           2
Mon-Fri,12noon to 4pm,7pm to 4am...              2
Mon-Sat,830am to 12noon(Sun                      2
Mon,Sat,930am...                                 2
Mon,2pm to 1130pm(Tue-Sun                        2
Mon,Sun...                                       2
Mon,11am to 12midnight...                        2
Mon,Tue,Wed,Fri,11am to 1130pm...                2
Mon,7am to 1030pm(Tue-Sun                        2
Mon,10am to 4am(Tue-Sun                          2
Mon-Sat,10am to 2pm(Sun                          2
Mon-Sat,2pm to 1030pm(Sun                        2
Mon,12noon to 1030pm(Tue-Sun                     2
Mon-Fri,12noon to 1145pm...                      2
Mon-Sat,12noon to 1030pm(Sun                     2
Mon,12noon to 330pm,7pm to 12midnight...         2
Mon,11am to 4pm,7pm to 1130pm(Tue-Sun            2
Mon-Sat,1145am...                                2
Mon,1230pm to 1030pm(Tue-Sun                     2
Mon,Tue,Wed,Thu,Sat,Sun,5pm to ...               2
Mon,Tue,Wed,Fri,Sat,Closed...                    2
Mon,12noon to 330pm,7pm to 1130pm...             2
Mon-Sat,12midnight to ...                        2
Mon,Tue,Wed,Thu,Sun,10am to ...                  2
Mon-Thu,1130am to 11pm...                        2
Mon,Tue,Wed,Thu,Sun,11am...                      2
Mon,11am to ...                                  2
Mon,1pm to 3am(Tue-Sun                           2
Mon-Fri,9am to 12midnight(Sat-Sun                2
Mon-Tue,11am to 12midnight...                    2
Mon,8am to 12midnight...                         2
Mon,1130am to ...                                2
Mon,830am to 830pm(Tue-Sun                       2
Mon,Tue,Wed,Thu,Sat,Sun,7am...                   2
Mon,12noon to 3pm,6pm to 11pm...                 2
Mon,Tue,Fri,Sat...                               2
Mon,930am to 930pm(Tue-Sun                       2
Mon,1130am to 12midnight...                      2
Mon,Wed,Thu,Fri,Sat,8am to ...                   2
Mon,12noon to 1am(Tue-Sun                        2
Mon-Fri,9am to 11pm(Sat-Sun                      2
Mon-Fri,12noon to 12midnight...                  2
Mon,11am to 3pm,7pm to 1130pm(Tue-Sun            2
Mon,10am to 930pm(Tue-Sun                        2
Mon-Thu,11am to 1130pm(Fri-Sun                   2
Mon,1130am to 11pm(Tue-Sun                       2
Mon-Sat,12noon to 11pm(Sun                       2
Mon,1130am to 1230AM(Tue-Sun                     2
Mon,12noon to 4pm,7pm to 11pm(Tue-Sun            2
Mon,1130am to 1130pm(Tue...                      2
Mon-Sat,12noon to 4pm(Sun                        2
Mon,9am to 930pm(Tue-Sun                         2
Mon-Fri,12noon to 3am(Sat-Sun                    2
Mon,12noon to 3pm,7pm to 11pm(Tue-Sun            2
Mon,3pm to 12midnight(Tue-Sun                    2
Mon,730pm to 330am(Tue-Sun                       2
Mon-Sat,5pm to 12midnight(Sun                    2
Mon-Sat,430pm to 11pm(Sun                        2
Mon-Fri,10am to 11pm(Sat-Sun                     2
Mon-Sat,2pm to 11pm(Sun                          2
Mon-Fri,11am to 11pm(Sat-Sun                     2
Mon-Fri,8am to 10pm(Sat-Sun                      2
Mon-Fri,8am to 12midnight...                     2
Mon-Thu,11am to 2am(Fri-Sun                      2
Mon,Tue,Wed,Thu,Sat,Sun,9am...                   2
Mon-Thu,11am to 3am(Fri-Sun                      2
Mon,Tue,Wed,Thu,Sat,Sun,11am...                  2
Mon,Wed,Thu,Sun,Closed...                        2
Mon,7am to 930pm(Tue-Sun                         2
Mon-Thu,11am to 130am(Fri-Sun                    2
Mon,12noon to 10pm(Tue-Sun                       2
Mon-Thu,9am to 12midnight(Fri-Sun                2
Mon-Sat,11am to 1130pm(Sun                       2
Mon,1pm to 11pm(Tue-Fri,1pm to ...               2
Mon-Fri,1130am to 1130pm...                      2
Mon-Fri,11am to 1am(Sat-Sun                      2
Mon-Thu,11am to 4am(Fri-Sun                      1
Mon-Fri,1230pm to 12midnight...                  1
Mon,11am to 1130pm(Tue,1130am to ...             1
Mon-Tue,1130am to 12midnight...                  1
Mon,Tue,Wed,Sun,11am to ...                      1
Mon,9am to 1am(Tue-Sun                           1
Mon,Tue,Thu,Fri,Sat,8am to 11pm...               1
Mon,11am to 4pm,6pm to 12midnight...             1
Mon,4pm to 12midnight(Tue-Sun                    1
Mon,1115am to 12midnight...                      1
Mon-Sat,630am to 930am(Sun                       1
Mon,12noon to 3pm,7pm to ...                     1
Mon-Thu,730am...                                 1
Mon,Closed(Tue,1230pm to 11pm...                 1
Mon,1130am to 4am(Tue-Sun                        1
Mon-Sat,12noon to 9pm(Sun                        1
Mon,Tue,Wed,Thu,Sat,Sun,5pm...                   1
Mon-Sat,5pm to 1130pm(Sun                        1
Mon,6pm to 12midnight(Tue-Sun                    1
Mon,930am to 12midnight...                       1
Mon,Tue,Wed,Sun,12midnight to ...                1
Mon,10am to 11pm(Tue-Thu,10am to ...             1
Mon,11am to 11pm(Tue-Fri,11am to ...             1
Mon-Thu,1130am to 1130pm(Fri-Sun                 1
Mon-Sat,1pm to ...                               1
Mon-Sat,530pm to 10pm...                         1
Mon,1130am to 3pm,7pm to 1130pm(Tue-Sun          1
Mon,Tue,Wed,Thu,Sun,12noon...                    1
Mon-Sat,1pm to 11pm(Sun                          1
Mon-Sat,1230pm to ...                            1
Mon,12noon to 1130pm...                          1
Mon-Fri,10am to 12midnight(Sat-Sun               1
Mon-Sat,9am to 4pm(Sun                           1
Mon-Fri,1130am to 12noon...                      1
Mon,7am to 1230pm,4pm to 930pm...                1
Mon,11am to 6am(Tue-Sun                          1
Mon,Tue,Wed,Thu,Sun,630pm to ...                 1
Mon,9am to 1pm,6pm to 9pm(Tue-Sun                1
Mon,Tue,Fri,Sat,Sun,12noon...                    1
Mon,12midnight...                                1
Mon,1030am to 2pm,4pm to 1030pm(Tue-Sun          1
Mon-Sat,9am to 4am(Sun                           1
Mon,1230pm to 11pm...                            1
Mon-Fri,1230pm to 1130pm...                      1
Mon,Tue,Wed,Thu,Sun,7pm to ...                   1
Mon-Sat,10am to 6pm(Sun                          1
Mon-Sat,830pm to 1030pm(Sun                      1
Mon-Fri,9am to 130am(Sat-Sun                     1
Mon,1130am to 130am(Tue,Wed...                   1
Mon-Sat,1230pm to 130am(Sun                      1
Mon,Tue,Wed,Fri,5pm to 10pm...                   1
Mon,1130am to 4pm,7pm to 1130pm(Tue-Sun          1
Mon-Thu,1030am to 9pm(Fri-Sun                    1
Mon-Sat,12noon to 6pm(Sun                        1
Mon,11am to 330pm,7pm to 12midnight...           1
Mon-Sat,11am to 230pm,6pm...                     1
Mon,Tue,Fri...                                   1
Mon-Fri,1230pm to 330pm,630pm...                 1
Mon-Thu,3pm to 3am(Fri-Sun                       1
Mon,Wed,Thu,Fri,Sat,Sun,3pm...                   1
Mon-Thu,1230pm to 1am(Fri-Sun                    1
Mon,Tue,Wed,Fri,Sat,Sun,11am...                  1
Mon-Fri,1130am to ...                            1
Mon,1130am to 330pm,7pm to 12midnight...         1
Mon,1230pm to 1230AM(Tue-Sun                     1
Mon-Fri,1130am...                                1
Mon,11am to 330pm,730pm to 1am(Tue-Sun           1
Mon-Thu,11am...                                  1
Mon,11am to 330pm,530pm to 11pm...               1
Mon,10am to 6pm(Tue-Sun                          1
Mon,Wed,Thu,Fri,Sat,Sun,8am to ...               1
Mon,730am to 830pm(Tue-Fri,730am to ...          1
Mon,9am to 12midnight(Tue-Sun                    1
Mon-Sat,1230pm to 1130pm(Sun                     1
Mon-Sat,7am to 8pm(Sun                           1
Mon-Wed,12noon to 4am(Thu-Sun                    1
Mon,Tue,Thu,2pm to 3am...                        1
Mon,12noon to 4pm,7pm to 1155pm(Tue-Sun          1
Mon-Sat,3pm to 10pm(Sun                          1
Mon,7am to 3pm,530pm to 930pm(Tue-Sun            1
Mon,Tue,Wed,Thu,Sat,2pm...                       1
Mon,745am to 930pm(Tue-Sun                       1
Mon,11am to 4pm,7pm to 12midnight(Tue-Sun        1
Mon-Sat,12noon to 630pm(Sun                      1
Mon,Wed,12midnight to 2am...                     1
Mon,12noon to 2pm,5pm to 945pm(Tue-Sun           1
Mon,9am to 8pm(Tue-Sat,9am to ...                1
Mon,10am to 4pm,7pm to 12midnight(Tue-Sun        1
Mon-Sat,11am to 2pm(Sun                          1
Mon,1030am to 4pm,7pm to 1115pm...               1
Mon-Fri,8am to 3pm(Sat,Closed(Sun                1
Mon,Fri...                                       1
Mon,11am to 930pm(Tue-Sun                        1
Mon-Sat,12noon to 5pm(Sun                        1
Mon-Thu,1pm to 2am(Fri-Sun                       1
Mon-Fri,430pm to ...                             1
Mon-Sat,1130am...                                1
Mon-Wed,10am to 11pm(Thu-Sun                     1
Mon-Fri,12noon to 1130pm(Sat-Sun                 1
Mon,10am to 3am(Tue-Sun                          1
Mon,11am to 230am(Tue-Sun                        1
Mon,Tue,Thu,Fri,Sat,Sun,4pm...                   1
Mon-Sat,7pm...                                   1
Mon-Sat,7am to 7pm(Sun                           1
Mon-Thu,4pm to 3am(Fri-Sun                       1
Mon-Tue,12noon to 1230AM(Wed-Sun                 1
Mon,Wed,Fri...                                   1
Mon-Thu,430pm to 130am(Fri-Sun                   1
Mon-Sat,1049am to 1155pm(Sun                     1
Mon-Thu,1230pm to 12midnight...                  1
Mon-Sat,11am to 4pm...                           1
Mon,12noon to 4pm,730pm to 1030pm...             1
Mon,12midnight to 4am,7pm to 12midnight...       1
Mon-Thu,9am to 2am...                            1
Mon-Thu,830am to ...                             1
Mon-Thu,9am to 11pm(Fri-Sun                      1
Mon-Sat,9am to 2am(Sun                           1
Mon-Fri,10am to ...                              1
Mon-Fri,10am to 1030pm(Sat-Sun                   1
Mon,3pm to 11pm(Tue-Sun                          1
Mon-Fri,6pm to ...                               1
Mon-Thu,11am to 1155pm(Fri-Sun                   1
Mon,830am to 930pm(Tue-Sun                       1
Mon-Sat,1030am to 1130pm(Sun                     1
Mon,Tue,Wed,Thu,Sun,8am to 3am...                1
Mon,1145am to 330pm,645pm to 1130pm...           1
Mon-Sat,9am to 1130pm(Sun                        1
Mon,12noon to 330pm,7pm to 11pm...               1
Mon,Tue,Thu,Fri,Sat,930am to ...                 1
Mon,4pm to 130am(Tue-Sun                         1
Mon-Sat,730am to 1130pm(Sun                      1
Mon,Thu,Fri,Sat,12noon to 3am...                 1
Mon-Fri,10am to 9pm(Sat-Sun                      1
Mon-Fri,12noon to 130am...                       1
Mon,Tue,Thu,Fri,Sun,10am to ...                  1
Mon-Fri,4pm to 12midnight(Sat-Sun                1
Mon-Fri,12noon to 4pm,7pm to ...                 1
Mon,Tue,Thu,Fri,Sat,Sun,10am...                  1
Mon,12noon to 330pm,8pm to ...                   1
Mon-Thu,6pm to 3am(Fri-Sun                       1
Mon-Thu,1230pm to 1130pm...                      1
Mon-Wed,11am to 1230pm...                        1
Mon-Thu,11am to 1145pm(Fri-Sun                   1
Mon,Thu,12noon to 3pm,7pm to 10pm...             1
Mon-Sat,7am to 630pm(Sun                         1
Mon,1030am to 330pm,630pm to 11pm...             1
Mon,Closed(Tue,11pm to 6am(Wed-Sun               1
Mon,Tue,Wed,Thu,Fri,Sun,12noon...                1
Mon-Fri,930am to 1030pm...                       1
Mon,Sat,11am to 10pm(Tue...                      1
Mon-Sat,1230pm...                                1
Mon,1030am to 1130pm(Tue-Sun                     1
Mon,11am to 4pm,7pm to ...                       1
Mon,Tue,Wed,Thu,Sun,9am to ...                   1
Mon-Sat,7pm to 2am(Sun                           1
Mon,Tue,Thu,Fri,Sat,Sun,1pm to ...               1
Mon,11am to 3pm...                               1
Mon,Thu,Fri,Sat,Sun,1pm to ...                   1
Mon,Fri,11am to 11pm(Tue...                      1
Mon,8am to 830pm(Tue-Fri,10am...                 1
Mon,12noon to 7pm(Tue-Sat,11am to 4pm...         1
Mon,Tue,Wed,Sat,Sun,8am to 11pm...               1
Mon,Tue,Thu,Fri,7am to ...                       1
Mon,10am to 7pm(Tue-Sat,Closed...                1
Mon,12midnight to 1am,1230pm...                  1
Mon,11am to 3pm,7pm to ...                       1
Mon,9am to 9pm(Tue-Fri,830am to 9pm...           1
Mon,Thu,Fri,Sat,Sun...                           1
Mon,1130am to 4pm,7pm to 11pm(Tue-Sun            1
Mon-Thu,12midnight to 1230AM...                  1
Mon,8am to 10pm(Tue-Sun                          1
Mon,10am to 12midnight...                        1
Mon,11am to 1230AM(Tue-Sun                       1
Mon-Sat,9am to 10pm(Sun                          1
Mon,5pm to 4am(Tue-Sun                           1
Mon,Sat...                                       1
Mon-Thu,230pm to 1230AM...                       1
Mon-Fri,1030am to 1130pm...                      1
Mon,4pm to 11pm(Tue-Fri,12noon to 11pm...        1
Mon,1pm to 1230AM(Tue-Sun                        1
Mon-Fri,12noon to 2am(Sat-Sun                    1
Mon,1130am to 330pm,630pm to 11pm...             1
Mon-Thu,10am to 130am(Fri-Sun                    1
Mon-Sat,8am to 12midnight(Sun                    1
Mon-Sat,430pm to 1030pm(Sun                      1
Mon,Tue,Sat...                                   1
Mon,Tue,Thu,Sat,Sun...                           1
Mon-Tue,12noon to 230am(Wed-Sun                  1
Mon-Sat,830am to 130am(Sun                       1
Mon-Fri,8am to 2pm(Sat,Closed(Sun                1
Mon,Tue,Wed,Thu,Sun,Closed...                    1
Mon-Sat,12noon to 130am(Sun                      1
Mon-Fri,7am to 12midnight...                     1
Mon-Sat,10am to 10pm(Sun                         1
Mon-Thu,12noon to 130am...                       1
Mon,6am to 11pm(Tue-Sun                          1
Mon,12noon to 330pm,630pm to 1130pm...           1
Mon,1130am to 330pm,6pm to ...                   1
Mon-Fri,1130am to 11pm...                        1
Mon-Fri,530pm to 1230AM...                       1
Mon,Wed,Sun,11am to 2am(Tue...                   1
Mon,3pm to 1158pm(Tue-Wed,3pm to ...             1
Mon,11am to 330pm,7pm to 1030pm(Tue-Sun          1
Mon,Wed,Thu,Closed...                            1
Mon-Fri,930am...                                 1
Mon-Thu,1130am to 11pm(Fri-Sun                   1
Mon,8am to 1130pm(Tue-Sun                        1
Mon,Tue,Thu,Fri,Sat,Sun,1pm...                   1
Mon,8am to 12noon,5pm to 1030pm...               1

In [80]:
raw_df["TIMING"].value_counts()

11am to 11pm                                        1255
11am to 12midnight                                   665
12noon to 12midnight                                 503
11am to 1130pm                                       325
10am to 10pm                                         296
Closed                                               288
10am to 11pm                                         242
10am to 12midnight                                   232
11am to 1230AM                                       206
12noon to 11pm                                       182
8am to 11pm                                          182
9am to 11pm                                          178
11am to 1am                                          178
9am to 12midnight                                    172
1130am to 1130pm                                     167
8am to 12midnight                                    164
12noon to 1am                                        144
12noon to 1130pm                                     139
7am to 11pm                                          133
9am to 9pm                                           133
11am to 10pm                                         131
1130am to 12midnight                                 128
9am to 10pm                                          127
8am to 1130pm                                        106
7am to 12midnight                                    106
8am to 10pm                                          105
11am to 4pm,7pm to 12midnight                        104
12noon to 1230AM                                     100
10am to 1130pm                                        96
9am to 1130pm                                         92
12noon to 4pm,7pm to 12midnight                       74
10am to 8pm                                           73
12noon to 130am                                       73
10am to 1230AM                                        70
11am to 330pm,7pm to 1130pm                           69
1130am to 1230AM                                      69
NA                                                    65
1130am to 11pm                                        63
10am to 1am                                           62
7am to 10pm                                           58
7am to 1130pm                                         55
11am to 130am                                         54
10am to 9pm                                           54
11am to 4am                                           53
11am to 4pm,7pm to 11pm                               53
12noon to 330pm,7pm to 1130pm                         52
1030am to 12midnight                                  52
11am to 2am                                           52
1030am to 1130pm                                      52
10am to 1030pm                                        52
11am to 3am                                           51
1030am to 1030pm                                      49
1030am to 1230AM                                      48
9am to 1030pm                                         46
12noon to 330pm,7pm to 12midnight                     44
1130am to 330pm,630pm to 1130pm                       44
1030am to 11pm                                        44
11am to 1030pm                                        44
11am to 3pm,7pm to 11pm                               44
11am to 9pm                                           43
12noon to 10pm                                        42
12noon to 2am                                         41
11am to 4pm,7pm to 1130pm                             41
24                                                    41
1130am to 330pm,7pm to 1130pm                         41
8am to 1030pm                                         40
12noon to 3am                                         39
12noon to 4am                                         39
10am to 7pm                                           39
4pm to 11pm                                           38
9am to 1am                                            38
9am to 1230AM                                         38
1pm to 12midnight                                     37
1130am to 1am                                         36
8am to 8pm                                            35
6pm to 12midnight                                     35
930am to 1130pm                                       35
8am to 9pm                                            34
12noon to 3pm,7pm to 12midnight                       33
830am to 1030pm                                       33
10am to 130am                                         33
9am to 8pm                                            32
11am to 3pm,6pm to 12midnight                         31
1pm to 11pm                                           31
10am to 6pm                                           31
11am to 330pm,7pm to 12midnight                       31
830am to 11pm                                         31
1130am to 130am                                       31
1pm to 1am                                            30
11am to 3pm,6pm to 11pm                               30
11am to 3pm,7pm to 12midnight                         28
4pm to 12midnight                                     28
1130am to 4pm,7pm to 12midnight                       28
1230pm to 1130pm                                      27
5pm to 11pm                                           27
11am to 330pm,7pm to 11pm                             26
12noon to 3pm,6pm to 12midnight                       26
930am to 12midnight                                   26
11am to 7pm                                           26
12noon to 4pm,7pm to 11pm                             26
6pm to 11pm                                           26
12noon to 3pm,7pm to 11pm                             25
5pm to 12midnight                                     25
6am to 12midnight                                     25
7pm to 4am                                            25
1230pm to 1230AM                                      25
1130am to 1030pm                                      24
730am to 11pm                                         23
8am to 1am                                            23
8am to 1230AM                                         23
12noon to 4pm,7pm to 1130pm                           23
9am to 7pm                                            22
830am to 12midnight                                   22
830am to 1130pm                                       22
7am to 1am                                            22
11am to 330pm,630pm to 1130pm                         21
1230pm to 12midnight                                  21
12noon to 330pm,7pm to 11pm                           21
11am to 1145pm                                        20
8am to 2am                                            20
730am to 1130pm                                       20
730am to 12midnight                                   20
5pm to 1130pm                                         20
11am to 3pm,7pm to 1130pm                             19
7am to 9pm                                            19
12noon to 1030pm                                      19
930am to 11pm                                         19
12noon to 330pm,7pm to 1230AM                         19
12noon to 4pm,6pm to 12midnight                       19
930am to 10pm                                         18
930am to 1030pm                                       18
12noon to 4pm,7pm to 1230AM                           18
1230pm to 11pm                                        18
2pm to 12midnight                                     18
730am to 1030pm                                       18
7am to 1030pm                                         18
11am to 8pm                                           18
12noon to 3pm,7pm to 1130pm                           17
1130am to 4am                                         17
7pm to 12midnight                                     17
9am to 6pm                                            17
7pm to 11pm                                           17
2pm to 11pm                                           17
6am to 10pm                                           17
7am to 1230AM                                         16
1130am to 330pm,7pm to 12midnight                     16
1pm to 1130pm                                         15
4pm to 1am                                            15
3pm to 11pm                                           15
730am to 10pm                                         15
11am to 4pm,6pm to 12midnight                         15
1030am to 1am                                         15
11am to 930pm                                         15
11am to 4pm,7pm to 1230AM                             14
1030am to 10pm                                        14
8am to 830pm                                          14
8am to 130am                                          14
1130am to 330pm,630pm to 12midnight                   13
6am to 11pm                                           13
4pm to 10pm                                           13
1230pm to 130am                                       13
6pm to 1am                                            13
1130am to 4pm,7pm to 1130pm                           13
12noon to 330pm,6pm to 12midnight                     13
2pm to 1130pm                                         13
930am to 1230AM                                       13
12noon to 330pm,630pm to 12midnight                   12
10am to 3am                                           12
10am to 930pm                                         12
7am to 4am                                            12
830am to 10pm                                         12
12noon to 330pm,630pm to 1130pm                       12
11am to 330pm,6pm to 12midnight                       12
12noon to 3pm,6pm to 11pm                             12
11am to 330pm,7pm to 1230AM                           12
11am to 4pm,6pm to 11pm                               11
9am to 4am                                            11
3pm to 12midnight                                     11
11am to 4pm,6pm to 1130pm                             11
12noon to 4pm,7pm to 1am                              11
12noon to 4pm,630pm to 12midnight                     11
9am to 930pm                                          11
5pm to 10pm                                           11
8am to 930pm                                          11
6pm to 4am                                            11
6pm to 1130pm                                         11
1130am to 4pm,630pm to 1130pm                         11
930am to 930pm                                        11
1130am to 3pm,630pm to 12midnight                     10
12noon to 3pm,6pm to 1130pm                           10
11am to 4pm,630pm to 1130pm                           10
830am to 830pm                                        10
6pm to 1230AM                                         10
1230pm to 1am                                         10
1130am to 3pm,7pm to 1130pm                           10
1130am to 330pm,7pm to 11pm                           10
4pm to 1230AM                                         10
11am to 3pm,6pm to 1130pm                             10
7pm to 5am                                            10
1030am to 130am                                       10
1130am to 330pm,6pm to 1130pm                          9
6am to 1am                                             9
12noon to 330pm,7pm to 1am                             9
930am to 9pm                                           9
11am to 330pm,630pm to 12midnight                      9
830am to 930pm                                         9
4pm to 1130pm                                          9
530pm to 12midnight                                    9
1130am to 10pm                                         9
12noon to 4pm,7pm to 130am                             9
8am to 7pm                                             9
7am to 8pm                                             9
930am to 1am                                           9
8am to 3am                                             9
6am to 1130pm                                          9
7am to 930pm                                           9
10am to 2am                                            8
11am to 330am                                          8
7pm to 1130pm                                          8
7am to 130am                                           8
1130am to 3pm,7pm to 11pm                              8
1pm to 3am                                             8
12noon to 9pm                                          8
11am to 330pm,630pm to 11pm                            8
6pm to 2am                                             8
12noon to 3pm,7pm to 1230AM                            8
830am to 9pm                                           8
6pm to 130am                                           8
4pm to 4am                                             8
1130am to 3am                                          8
11am to 330pm,6pm to 1130pm                            8
10am to 4am                                            8
9am to 2am                                             8
                                                       8
1230pm to 330pm,7pm to 12midnight                      8
5pm to 2am                                             8
1130am to 330pm,730pm to 1130pm                        8
12noon to 330am                                        8
12noon to 4pm,6pm to 1130pm                            8
5am to 1am                                             7
12noon to 330pm,6pm to 11pm                            7
1130am to 3pm,630pm to 11pm                            7
12noon to 4pm,7pm to 3am                               7
1130am to 330pm,7pm to 1230AM                          7
12noon to 330pm,630pm to 1230AM                        7
4pm to 130am                                           7
2pm to 1am                                             7
1230pm to 1030pm                                       7
11am to 830pm                                          7
7am to 7pm                                             7
9am to 830pm                                           7
11am to 5am                                            7
430pm to 12midnight                                    7
1130am to 1145pm                                       7
12midnight to 1am,12noon to 12midnight                 7
1130am to 4pm,630pm to 12midnight                      7
130pm to 12midnight                                    7
11am to 330pm,6pm to 11pm                              7
12noon to 4pm,6pm to 11pm                              7
10am to 1145pm                                         7
6am to 1230AM                                          7
11am to 1245AM                                         7
12noon to 4pm,7pm to 2am                               6
630pm to 1130pm                                        6
11am to 1215AM                                         6
1130am to 3pm,6pm to 11pm                              6
3pm to 1am                                             6
630am to 1130pm                                        6
2pm to 10pm                                            6
11am to 3pm,630pm to 12midnight                        6
1pm to 10pm                                            6
12noon to 1145pm                                       6
1230pm to 330pm,7pm to 1130pm                          6
1030am to 630pm                                        6
11am to 1115pm                                         6
12noon to 330pm,6pm to 1130pm                          6
10am to 830pm                                          6
930am to 630pm                                         6
1030am to 930pm                                        6
1130am to 2am                                          6
11am to 3pm,6pm to 10pm                                6
11am to 4pm,630pm to 11pm                              6
130pm to 11pm                                          6
730am to 9pm                                           6
7am to 5am                                             6
630pm to 12midnight                                    6
11am to 4pm                                            6
12noon to 8pm                                          6
12noon to 930pm                                        6
1pm to 2am                                             6
730am to 1230AM                                        6
1130am to 330pm,6pm to 12midnight                      6
6am to 4am                                             5
7pm to 3am                                             5
12noon to 4pm,630pm to 1130pm                          5
530pm to 130am                                         5
10am to 730pm                                          5
12noon to 4pm,7pm to 1145pm                            5
11am to 5pm                                            5
8am to 4am                                             5
8am to 6pm                                             5
12noon to 7pm                                          5
12noon to 330pm,7pm to 4am                             5
730am to 830pm                                         5
5am to 12midnight                                      5
12noon to 3pm,630pm to 11pm                            5
11am to 4pm,7pm to 1145pm                              5
11am to 6pm                                            5
130pm to 130am                                         5
630am to 12midnight                                    5
5pm to 1230AM                                          5
1130am to 330pm,730pm to 12midnight                    5
7am to 2am                                             5
1pm to 1230AM                                          5
12noon to 5pm,7pm to 12midnight                        5
11am to 12noon                                         5
11am to 4pm,7pm to 1am                                 5
830am to 8pm                                           5
7pm to 1am                                             5
430pm to 11pm                                          5
12noon to 5pm                                          5
12noon to 3pm,730pm to 1130pm                          5
1030am to 9pm                                          5
630pm to 1am                                           5
1130am to 230am                                        5
7am to 1145pm                                          5
12noon to 4pm,730pm to 1130pm                          5
4pm to 2am                                             5
12noon to 330pm,7pm to 1030pm                          5
11am to 330pm,6pm to 1230AM                            5
830am to 1230AM                                        5
1030am to 730pm                                        5
9am to 1145pm                                          5
6am to 1030pm                                          5
1130am to 4pm,6pm to 1130pm                            4
3pm to 1030pm                                          4
11am to 3pm,7pm to 1230AM                              4
5am to 11pm                                            4
1130am to 4pm,7pm to 11pm                              4
7pm to 130am                                           4
3pm to 1130pm                                          4
12midnight to 1am,11am to 12midnight                   4
1pm to 4pm,7pm to 12midnight                           4
11am to 630pm                                          4
5pm to 1030pm                                          4
12noon to 330pm,7pm to 12midnight...                   4
12noon to 3pm,7pm to 1am                               4
430pm to 1130pm                                        4
5pm to 5am                                             4
1130am to 3pm,6pm to 1130pm                            4